# PATSTAT (placeholder) {#patstat}
\index{patstat}

This chapter provides an introduction to the European Patent Office `World Patent Statistical Database` (PATSTAT). PATSTAT provides the international baselines for the production of patent statistics and is widely used by patent offices and in academic circles. 

PATSTAT is based on the central EPO documentation database (DOCDB). It consists of a set of tables that can be used using a key field using Structured Query Language (SQL) or MySQL or wrappers in R, Python or other languages. 

PATSTAT is available in three main forms. 

- As a standalone set of tables (delivered on an external hard drive)
- As PATSTAT online 
- As IISC PATSTAT, for VantagePoint users

In this chapter we will focus on PATSTAT Online as the easiest way to get started with PATSTAT without the need to set up an server running an SQL or MySQL database. We will cover the use of PATSTAT as a standalone database in a later section. 

### Getting Started

To get started with PATSTAT you need to create an account with the EPO and register for a free PATSTAT online account. 


```{r}

```


### Recipe 1

Retrieve all data about filings in a country

### Recipe 2 IPC based analysis

### Recipe 3 Patent Family Analysis

### Recipe 4 Applicants

### Recipe 5 Inventors

### Recipe 6 Non Patent Literature
