<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>The WIPO Patent Analytics Handbook</title>
  <meta name="description" content="This is a working draft of the WIPO Patent Analytics Handbook.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="The WIPO Patent Analytics Handbook" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a working draft of the WIPO Patent Analytics Handbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="The WIPO Patent Analytics Handbook" />
  
  <meta name="twitter:description" content="This is a working draft of the WIPO Patent Analytics Handbook." />
  

<meta name="author" content="Paul Oldham">


<meta name="date" content="2018-09-24">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="literature.html">
<link rel="next" href="patstat.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.2/htmlwidgets.js"></script>
<script src="libs/d3-4.5.0/d3.min.js"></script>
<script src="libs/sankey-1/sankey.js"></script>
<script src="libs/sankeyNetwork-binding-0.4/sankeyNetwork.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.0.1/leaflet.js"></script>

<script>
/* ========================================================================
 * Bootstrap: transition.js v3.3.7
 * http://getbootstrap.com/javascript/#transitions
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */


+function ($) {
  'use strict';

  // CSS TRANSITION SUPPORT (Shoutout: http://www.modernizr.com/)
  // ============================================================

  function transitionEnd() {
    var el = document.createElement('bootstrap')

    var transEndEventNames = {
      WebkitTransition : 'webkitTransitionEnd',
      MozTransition    : 'transitionend',
      OTransition      : 'oTransitionEnd otransitionend',
      transition       : 'transitionend'
    }

    for (var name in transEndEventNames) {
      if (el.style[name] !== undefined) {
        return { end: transEndEventNames[name] }
      }
    }

    return false // explicit for ie8 (  ._.)
  }

  // http://blog.alexmaccaw.com/css-transitions
  $.fn.emulateTransitionEnd = function (duration) {
    var called = false
    var $el = this
    $(this).one('bsTransitionEnd', function () { called = true })
    var callback = function () { if (!called) $($el).trigger($.support.transition.end) }
    setTimeout(callback, duration)
    return this
  }

  $(function () {
    $.support.transition = transitionEnd()

    if (!$.support.transition) return

    $.event.special.bsTransitionEnd = {
      bindType: $.support.transition.end,
      delegateType: $.support.transition.end,
      handle: function (e) {
        if ($(e.target).is(this)) return e.handleObj.handler.apply(this, arguments)
      }
    }
  })

}(jQuery);
</script>
<script>
/* ========================================================================
 * Bootstrap: collapse.js v3.3.7
 * http://getbootstrap.com/javascript/#collapse
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */

/* jshint latedef: false */

+function ($) {
  'use strict';

  // COLLAPSE PUBLIC CLASS DEFINITION
  // ================================

  var Collapse = function (element, options) {
    this.$element      = $(element)
    this.options       = $.extend({}, Collapse.DEFAULTS, options)
    this.$trigger      = $('[data-toggle="collapse"][href="#' + element.id + '"],' +
                           '[data-toggle="collapse"][data-target="#' + element.id + '"]')
    this.transitioning = null

    if (this.options.parent) {
      this.$parent = this.getParent()
    } else {
      this.addAriaAndCollapsedClass(this.$element, this.$trigger)
    }

    if (this.options.toggle) this.toggle()
  }

  Collapse.VERSION  = '3.3.7'

  Collapse.TRANSITION_DURATION = 350

  Collapse.DEFAULTS = {
    toggle: true
  }

  Collapse.prototype.dimension = function () {
    var hasWidth = this.$element.hasClass('width')
    return hasWidth ? 'width' : 'height'
  }

  Collapse.prototype.show = function () {
    if (this.transitioning || this.$element.hasClass('in')) return

    var activesData
    var actives = this.$parent && this.$parent.children('.panel').children('.in, .collapsing')

    if (actives && actives.length) {
      activesData = actives.data('bs.collapse')
      if (activesData && activesData.transitioning) return
    }

    var startEvent = $.Event('show.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    if (actives && actives.length) {
      Plugin.call(actives, 'hide')
      activesData || actives.data('bs.collapse', null)
    }

    var dimension = this.dimension()

    this.$element
      .removeClass('collapse')
      .addClass('collapsing')[dimension](0)
      .attr('aria-expanded', true)

    this.$trigger
      .removeClass('collapsed')
      .attr('aria-expanded', true)

    this.transitioning = 1

    var complete = function () {
      this.$element
        .removeClass('collapsing')
        .addClass('collapse in')[dimension]('')
      this.transitioning = 0
      this.$element
        .trigger('shown.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    var scrollSize = $.camelCase(['scroll', dimension].join('-'))

    this.$element
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)[dimension](this.$element[0][scrollSize])
  }

  Collapse.prototype.hide = function () {
    if (this.transitioning || !this.$element.hasClass('in')) return

    var startEvent = $.Event('hide.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    var dimension = this.dimension()

    this.$element[dimension](this.$element[dimension]())[0].offsetHeight

    this.$element
      .addClass('collapsing')
      .removeClass('collapse in')
      .attr('aria-expanded', false)

    this.$trigger
      .addClass('collapsed')
      .attr('aria-expanded', false)

    this.transitioning = 1

    var complete = function () {
      this.transitioning = 0
      this.$element
        .removeClass('collapsing')
        .addClass('collapse')
        .trigger('hidden.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    this.$element
      [dimension](0)
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)
  }

  Collapse.prototype.toggle = function () {
    this[this.$element.hasClass('in') ? 'hide' : 'show']()
  }

  Collapse.prototype.getParent = function () {
    return $(this.options.parent)
      .find('[data-toggle="collapse"][data-parent="' + this.options.parent + '"]')
      .each($.proxy(function (i, element) {
        var $element = $(element)
        this.addAriaAndCollapsedClass(getTargetFromTrigger($element), $element)
      }, this))
      .end()
  }

  Collapse.prototype.addAriaAndCollapsedClass = function ($element, $trigger) {
    var isOpen = $element.hasClass('in')

    $element.attr('aria-expanded', isOpen)
    $trigger
      .toggleClass('collapsed', !isOpen)
      .attr('aria-expanded', isOpen)
  }

  function getTargetFromTrigger($trigger) {
    var href
    var target = $trigger.attr('data-target')
      || (href = $trigger.attr('href')) && href.replace(/.*(?=#[^\s]+$)/, '') // strip for ie7

    return $(target)
  }


  // COLLAPSE PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this   = $(this)
      var data    = $this.data('bs.collapse')
      var options = $.extend({}, Collapse.DEFAULTS, $this.data(), typeof option == 'object' && option)

      if (!data && options.toggle && /show|hide/.test(option)) options.toggle = false
      if (!data) $this.data('bs.collapse', (data = new Collapse(this, options)))
      if (typeof option == 'string') data[option]()
    })
  }

  var old = $.fn.collapse

  $.fn.collapse             = Plugin
  $.fn.collapse.Constructor = Collapse


  // COLLAPSE NO CONFLICT
  // ====================

  $.fn.collapse.noConflict = function () {
    $.fn.collapse = old
    return this
  }


  // COLLAPSE DATA-API
  // =================

  $(document).on('click.bs.collapse.data-api', '[data-toggle="collapse"]', function (e) {
    var $this   = $(this)

    if (!$this.attr('data-target')) e.preventDefault()

    var $target = getTargetFromTrigger($this)
    var data    = $target.data('bs.collapse')
    var option  = data ? 'toggle' : $this.data()

    Plugin.call($target, option)
  })

}(jQuery);
</script>
<script>
window.initializeCodeFolding = function(show) {

  // handlers for show-all and hide all
  $("#rmd-show-all-code").click(function() {
    $('div.r-code-collapse').each(function() {
      $(this).collapse('show');
    });
  });
  $("#rmd-hide-all-code").click(function() {
    $('div.r-code-collapse').each(function() {
      $(this).collapse('hide');
    });
  });

  // index for unique code element ids
  var currentIndex = 1;

  // select all R code blocks
  var rCodeBlocks = $('pre.sourceCode, pre.r, pre.python, pre.bash, pre.sql, pre.cpp, pre.stan, pre.js');
  rCodeBlocks.each(function() {

    // create a collapsable div to wrap the code in
    var div = $('<div class="collapse r-code-collapse"></div>');
    if (show)
      div.addClass('in');
    var id = 'rcode-643E0F36' + currentIndex++;
    div.attr('id', id);
    $(this).before(div);
    $(this).detach().appendTo(div);

    // add a show code button right above
    var showCodeText = $('<span>' + (show ? 'Hide' : 'Code') + '</span>');
    var showCodeButton = $('<button type="button" class="btn btn-default btn-xs code-folding-btn pull-right"></button>');
    showCodeButton.append(showCodeText);
    showCodeButton
        .attr('data-toggle', 'collapse')
        .attr('data-target', '#' + id)
        .attr('aria-expanded', show)
        .attr('aria-controls', id);

    var buttonRow = $('<div class="row"></div>');
    var buttonCol = $('<div class="col-md-12"></div>');

    buttonCol.append(showCodeButton);
    buttonRow.append(buttonCol);

    div.before(buttonRow);

    // update state of button on show/hide
    div.on('hidden.bs.collapse', function () {
      showCodeText.text('Code');
    });
    div.on('show.bs.collapse', function () {
      showCodeText.text('Hide');
    });
  });

}
</script>
<script>
/* ========================================================================
 * Bootstrap: dropdown.js v3.3.7
 * http://getbootstrap.com/javascript/#dropdowns
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */


+function ($) {
  'use strict';

  // DROPDOWN CLASS DEFINITION
  // =========================

  var backdrop = '.dropdown-backdrop'
  var toggle   = '[data-toggle="dropdown"]'
  var Dropdown = function (element) {
    $(element).on('click.bs.dropdown', this.toggle)
  }

  Dropdown.VERSION = '3.3.7'

  function getParent($this) {
    var selector = $this.attr('data-target')

    if (!selector) {
      selector = $this.attr('href')
      selector = selector && /#[A-Za-z]/.test(selector) && selector.replace(/.*(?=#[^\s]*$)/, '') // strip for ie7
    }

    var $parent = selector && $(selector)

    return $parent && $parent.length ? $parent : $this.parent()
  }

  function clearMenus(e) {
    if (e && e.which === 3) return
    $(backdrop).remove()
    $(toggle).each(function () {
      var $this         = $(this)
      var $parent       = getParent($this)
      var relatedTarget = { relatedTarget: this }

      if (!$parent.hasClass('open')) return

      if (e && e.type == 'click' && /input|textarea/i.test(e.target.tagName) && $.contains($parent[0], e.target)) return

      $parent.trigger(e = $.Event('hide.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $this.attr('aria-expanded', 'false')
      $parent.removeClass('open').trigger($.Event('hidden.bs.dropdown', relatedTarget))
    })
  }

  Dropdown.prototype.toggle = function (e) {
    var $this = $(this)

    if ($this.is('.disabled, :disabled')) return

    var $parent  = getParent($this)
    var isActive = $parent.hasClass('open')

    clearMenus()

    if (!isActive) {
      if ('ontouchstart' in document.documentElement && !$parent.closest('.navbar-nav').length) {
        // if mobile we use a backdrop because click events don't delegate
        $(document.createElement('div'))
          .addClass('dropdown-backdrop')
          .insertAfter($(this))
          .on('click', clearMenus)
      }

      var relatedTarget = { relatedTarget: this }
      $parent.trigger(e = $.Event('show.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $this
        .trigger('focus')
        .attr('aria-expanded', 'true')

      $parent
        .toggleClass('open')
        .trigger($.Event('shown.bs.dropdown', relatedTarget))
    }

    return false
  }

  Dropdown.prototype.keydown = function (e) {
    if (!/(38|40|27|32)/.test(e.which) || /input|textarea/i.test(e.target.tagName)) return

    var $this = $(this)

    e.preventDefault()
    e.stopPropagation()

    if ($this.is('.disabled, :disabled')) return

    var $parent  = getParent($this)
    var isActive = $parent.hasClass('open')

    if (!isActive && e.which != 27 || isActive && e.which == 27) {
      if (e.which == 27) $parent.find(toggle).trigger('focus')
      return $this.trigger('click')
    }

    var desc = ' li:not(.disabled):visible a'
    var $items = $parent.find('.dropdown-menu' + desc)

    if (!$items.length) return

    var index = $items.index(e.target)

    if (e.which == 38 && index > 0)                 index--         // up
    if (e.which == 40 && index < $items.length - 1) index++         // down
    if (!~index)                                    index = 0

    $items.eq(index).trigger('focus')
  }


  // DROPDOWN PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this = $(this)
      var data  = $this.data('bs.dropdown')

      if (!data) $this.data('bs.dropdown', (data = new Dropdown(this)))
      if (typeof option == 'string') data[option].call($this)
    })
  }

  var old = $.fn.dropdown

  $.fn.dropdown             = Plugin
  $.fn.dropdown.Constructor = Dropdown


  // DROPDOWN NO CONFLICT
  // ====================

  $.fn.dropdown.noConflict = function () {
    $.fn.dropdown = old
    return this
  }


  // APPLY TO STANDARD DROPDOWN ELEMENTS
  // ===================================

  $(document)
    .on('click.bs.dropdown.data-api', clearMenus)
    .on('click.bs.dropdown.data-api', '.dropdown form', function (e) { e.stopPropagation() })
    .on('click.bs.dropdown.data-api', toggle, Dropdown.prototype.toggle)
    .on('keydown.bs.dropdown.data-api', toggle, Dropdown.prototype.keydown)
    .on('keydown.bs.dropdown.data-api', '.dropdown-menu', Dropdown.prototype.keydown)

}(jQuery);
</script>
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
.row { display: flex; }
.collapse { display: none; }
.in { display:block }
.pull-right > .dropdown-menu {
    right: 0;
    left: auto;
}
.open > .dropdown-menu {
    display: block;
}
.dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 160px;
    padding: 5px 0;
    margin: 2px 0 0;
    font-size: 14px;
    text-align: left;
    list-style: none;
    background-color: #fff;
    -webkit-background-clip: padding-box;
    background-clip: padding-box;
    border: 1px solid #ccc;
    border: 1px solid rgba(0,0,0,.15);
    border-radius: 4px;
    -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
    box-shadow: 0 6px 12px rgba(0,0,0,.175);
}
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>


<script>
document.write('<div class="btn-group pull-right" style="position: absolute; top: 20%; right: 2%; z-index: 200"><button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" data-_extension-text-contrast=""><span>Code</span> <span class="caret"></span></button><ul class="dropdown-menu" style="min-width: 50px;"><li><a id="rmd-show-all-code" href="#">Show All Code</a></li><li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li></ul></div>')
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The WIPO Patent Analytics Handbook</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note to Readers</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="" data-path="acknowlegements.html"><a href="acknowlegements.html"><i class="fa fa-check"></i>Acknowlegements</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="how-to-use-the-handbook.html"><a href="how-to-use-the-handbook.html"><i class="fa fa-check"></i>How to use the Handbook</a><ul>
<li class="chapter" data-level="0.0.1" data-path="how-to-use-the-handbook.html"><a href="how-to-use-the-handbook.html#datasets"><i class="fa fa-check"></i><b>0.0.1</b> Datasets</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="literature.html"><a href="literature.html"><i class="fa fa-check"></i><b>2</b> Scientific Literature</a><ul>
<li class="chapter" data-level="2.1" data-path="literature.html"><a href="literature.html#accessing-the-scientific-literature"><i class="fa fa-check"></i><b>2.1</b> Accessing the Scientific Literature</a></li>
<li class="chapter" data-level="2.2" data-path="literature.html"><a href="literature.html#searching-literature-databases"><i class="fa fa-check"></i><b>2.2</b> Searching Literature Databases</a><ul>
<li class="chapter" data-level="2.2.1" data-path="literature.html"><a href="literature.html#stemming"><i class="fa fa-check"></i><b>2.2.1</b> Stemming</a></li>
<li class="chapter" data-level="2.2.2" data-path="literature.html"><a href="literature.html#using-search-operators"><i class="fa fa-check"></i><b>2.2.2</b> Using Search Operators</a></li>
<li class="chapter" data-level="2.2.3" data-path="literature.html"><a href="literature.html#proximity-operators"><i class="fa fa-check"></i><b>2.2.3</b> Proximity Operators</a></li>
<li class="chapter" data-level="2.2.4" data-path="literature.html"><a href="literature.html#regular-expressions"><i class="fa fa-check"></i><b>2.2.4</b> Regular Expressions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="literature.html"><a href="literature.html#precision-vs.recall"><i class="fa fa-check"></i><b>2.3</b> Precision vs. Recall</a></li>
<li class="chapter" data-level="2.4" data-path="literature.html"><a href="literature.html#processing-scientific-literature"><i class="fa fa-check"></i><b>2.4</b> Processing Scientific Literature</a></li>
<li class="chapter" data-level="2.5" data-path="literature.html"><a href="literature.html#visualizing-the-scientific-literature"><i class="fa fa-check"></i><b>2.5</b> Visualizing the Scientific Literature</a><ul>
<li class="chapter" data-level="2.5.1" data-path="literature.html"><a href="literature.html#dashboards"><i class="fa fa-check"></i><b>2.5.1</b> Dashboards</a></li>
<li class="chapter" data-level="2.5.2" data-path="literature.html"><a href="literature.html#network-visualisation"><i class="fa fa-check"></i><b>2.5.2</b> Network Visualisation</a></li>
<li class="chapter" data-level="2.5.3" data-path="literature.html"><a href="literature.html#other-forms-of-visualisation"><i class="fa fa-check"></i><b>2.5.3</b> Other forms of visualisation</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="literature.html"><a href="literature.html#linking-the-scientific-literature-with-patent-analysis"><i class="fa fa-check"></i><b>2.6</b> Linking the Scientific Literature with Patent Analysis</a><ul>
<li class="chapter" data-level="2.6.1" data-path="literature.html"><a href="literature.html#mapping-authors-to-inventors"><i class="fa fa-check"></i><b>2.6.1</b> Mapping Authors to Inventors</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="literature.html"><a href="literature.html#linking-citations-with-patent-literature"><i class="fa fa-check"></i><b>2.7</b> Linking Citations with Patent Literature</a></li>
<li class="chapter" data-level="2.8" data-path="literature.html"><a href="literature.html#conclusion"><i class="fa fa-check"></i><b>2.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="patents.html"><a href="patents.html"><i class="fa fa-check"></i><b>3</b> Counting Patent Data</a><ul>
<li class="chapter" data-level="3.1" data-path="patents.html"><a href="patents.html#the-structure-of-patent-numbers"><i class="fa fa-check"></i><b>3.1</b> The structure of patent numbers</a><ul>
<li class="chapter" data-level="3.1.1" data-path="patents.html"><a href="patents.html#the-country-code"><i class="fa fa-check"></i><b>3.1.1</b> The country code</a></li>
<li class="chapter" data-level="3.1.2" data-path="patents.html"><a href="patents.html#the-numeric-identifier"><i class="fa fa-check"></i><b>3.1.2</b> The numeric identifier</a></li>
<li class="chapter" data-level="3.1.3" data-path="patents.html"><a href="patents.html#kind-codes"><i class="fa fa-check"></i><b>3.1.3</b> Kind Codes</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="patents.html"><a href="patents.html#preparing-to-count-patent-data"><i class="fa fa-check"></i><b>3.2</b> Preparing to Count Patent Data</a></li>
<li class="chapter" data-level="3.3" data-path="patents.html"><a href="patents.html#counting-priority-or-first-filings"><i class="fa fa-check"></i><b>3.3</b> Counting Priority or First Filings</a></li>
<li class="chapter" data-level="3.4" data-path="patents.html"><a href="patents.html#counting-priority-applications"><i class="fa fa-check"></i><b>3.4</b> Counting Priority Applications</a></li>
<li class="chapter" data-level="3.5" data-path="patents.html"><a href="patents.html#counting-applications"><i class="fa fa-check"></i><b>3.5</b> Counting Applications</a><ul>
<li class="chapter" data-level="3.5.1" data-path="patents.html"><a href="patents.html#mapping-publications"><i class="fa fa-check"></i><b>3.5.1</b> Mapping Publications</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="patents.html"><a href="patents.html#trends-by-country-using-publication-data"><i class="fa fa-check"></i><b>3.6</b> Trends by Country using Publication Data</a></li>
<li class="chapter" data-level="3.7" data-path="patents.html"><a href="patents.html#patent-families"><i class="fa fa-check"></i><b>3.7</b> Patent Families</a></li>
<li class="chapter" data-level="3.8" data-path="patents.html"><a href="patents.html#forecasting-patent-activity"><i class="fa fa-check"></i><b>3.8</b> Forecasting Patent Activity</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="patstat.html"><a href="patstat.html"><i class="fa fa-check"></i><b>4</b> PATSTAT (placeholder)</a></li>
<li class="chapter" data-level="5" data-path="indicators.html"><a href="indicators.html"><i class="fa fa-check"></i><b>5</b> Indicators (placeholder)</a></li>
<li class="chapter" data-level="6" data-path="textmining.html"><a href="textmining.html"><i class="fa fa-check"></i><b>6</b> Text Mining (placeholder)</a></li>
<li class="chapter" data-level="7" data-path="geocoding.html"><a href="geocoding.html"><i class="fa fa-check"></i><b>7</b> Geocoding</a><ul>
<li class="chapter" data-level="7.0.1" data-path="geocoding.html"><a href="geocoding.html#getting-started"><i class="fa fa-check"></i><b>7.0.1</b> Getting Started</a></li>
<li class="chapter" data-level="7.0.2" data-path="geocoding.html"><a href="geocoding.html#getting-set-up-with-the-google-maps-api"><i class="fa fa-check"></i><b>7.0.2</b> Getting set up with the Google Maps API</a></li>
<li class="chapter" data-level="7.0.3" data-path="geocoding.html"><a href="geocoding.html#using-the-api"><i class="fa fa-check"></i><b>7.0.3</b> Using the API</a></li>
<li class="chapter" data-level="7.0.4" data-path="geocoding.html"><a href="geocoding.html#the-source-data"><i class="fa fa-check"></i><b>7.0.4</b> The Source Data</a></li>
<li class="chapter" data-level="7.1" data-path="geocoding.html"><a href="geocoding.html#lookup-the-records"><i class="fa fa-check"></i><b>7.1</b> Lookup the Records</a><ul>
<li class="chapter" data-level="7.1.1" data-path="geocoding.html"><a href="geocoding.html#using-placement"><i class="fa fa-check"></i><b>7.1.1</b> Using placement</a></li>
<li class="chapter" data-level="7.1.2" data-path="geocoding.html"><a href="geocoding.html#using-ggmap"><i class="fa fa-check"></i><b>7.1.2</b> Using ggmap</a></li>
<li class="chapter" data-level="7.1.3" data-path="geocoding.html"><a href="geocoding.html#using-googleway"><i class="fa fa-check"></i><b>7.1.3</b> Using Googleway</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="geocoding.html"><a href="geocoding.html#reviewing-initial-results"><i class="fa fa-check"></i><b>7.2</b> Reviewing Initial Results</a><ul>
<li class="chapter" data-level="7.2.1" data-path="geocoding.html"><a href="geocoding.html#tackling-abbreviations"><i class="fa fa-check"></i><b>7.2.1</b> Tackling Abbreviations</a></li>
<li class="chapter" data-level="7.2.2" data-path="geocoding.html"><a href="geocoding.html#lookup-edited-names"><i class="fa fa-check"></i><b>7.2.2</b> Lookup edited names</a></li>
<li class="chapter" data-level="7.2.3" data-path="geocoding.html"><a href="geocoding.html#bringing-the-data-together"><i class="fa fa-check"></i><b>7.2.3</b> Bringing the data together</a></li>
<li class="chapter" data-level="7.2.4" data-path="geocoding.html"><a href="geocoding.html#assessing-the-quality-of-geocoding"><i class="fa fa-check"></i><b>7.2.4</b> Assessing the Quality of Geocoding</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="geocoding.html"><a href="geocoding.html#preprocess-the-data-and-rerun-the-query"><i class="fa fa-check"></i><b>7.3</b> Preprocess the Data and Rerun the Query</a><ul>
<li class="chapter" data-level="7.3.1" data-path="geocoding.html"><a href="geocoding.html#duplicated-affiliation-names"><i class="fa fa-check"></i><b>7.3.1</b> Duplicated Affiliation Names</a></li>
<li class="chapter" data-level="7.3.2" data-path="geocoding.html"><a href="geocoding.html#quickly-mapping-the-data"><i class="fa fa-check"></i><b>7.3.2</b> Quickly Mapping the Data</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="geocoding.html"><a href="geocoding.html#round-up"><i class="fa fa-check"></i><b>7.4</b> Round Up</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>8</b> References</a></li>
<li class="chapter" data-level="9" data-path="machinelearning.html"><a href="machinelearning.html"><i class="fa fa-check"></i><b>9</b> Machine Learning (placeholder)</a></li>
<li class="chapter" data-level="10" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>10</b> Patent Classfication (placeholder)</a></li>
<li class="chapter" data-level="11" data-path="citations.html"><a href="citations.html"><i class="fa fa-check"></i><b>11</b> Patent Citations (placeholder)</a></li>
<li class="chapter" data-level="12" data-path="social.html"><a href="social.html"><i class="fa fa-check"></i><b>12</b> Social Media and Patent Analytics (placeholder)</a></li>
<li class="divider"></li>
<li><a href="https://github.com/wipo-analytics/handbook" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The WIPO Patent Analytics Handbook</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="patents" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Counting Patent Data</h1>
<p>This chapter provides an in depth introduction to the development of descriptive patent statistics. While many readers will be familiar with patent statistics and the OECD Patents Statistics Manual is an important resource for thinking about patent statistics, to date a step by step approach to creating patent counts using real world data has been lacking <span class="citation">(<em>OECD Patent Statistics Manual</em> <a href="#ref-OECD_2009">2009</a>)</span>. This chapter aims to fill this gap by working up from the analysis of the structure of patent numbers through to the creation of counts priority or first filings. This is followed by exploration of patent families and concludes by graphing patent trends.</p>
<p>The Chapter makes extensive use of the drones patent dataset and instructions on how to install it are provided the How to Use the Handbook section at the front of the book.</p>
<!--to do Readers of this chapter online will be able to access the code and functions used to create the counts by selecting the `Code` icon.-->
<div id="the-structure-of-patent-numbers" class="section level2">
<h2><span class="header-section-number">3.1</span> The structure of patent numbers</h2>
<p>Patent numbers are the key identifiers for patent documents. At the time of writing there are presently 107 million patent and related documents within the European Patent Office central DOCDB. The key to working with and counting these documents is an understanding of the structure of patent numbers.</p>
<p>Table <a href="patents.html#tab:numbers">3.1</a> presents the principle formats of patent numbers as they are commonly retrieved from patent databases.</p>
<table>
<caption><span id="tab:numbers">Table 3.1: </span>Examples of Types of Patent Numbers</caption>
<thead>
<tr class="header">
<th align="left">priority_number</th>
<th align="left">application_number</th>
<th align="left">publication_number</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">US2016578323F 2016-09-20</td>
<td align="left">US2016578323F 2016-09-20</td>
<td align="left">USD801224S1</td>
</tr>
<tr class="even">
<td align="left">US15360203A 2016-11-23</td>
<td align="left">US15360203A 2016-11-23</td>
<td align="left">US9807726B1</td>
</tr>
<tr class="odd">
<td align="left">US62133061P 2015-03-13</td>
<td align="left">US15069675A 2016-03-14</td>
<td align="left">US9804596B1</td>
</tr>
<tr class="even">
<td align="left">US14622134A 2015-02-13</td>
<td align="left">US14622134A 2015-02-13</td>
<td align="left">US9802728B1</td>
</tr>
<tr class="odd">
<td align="left">JP2015122335A 2015-06-17; WO2016JP67809A 2016-06-15</td>
<td align="left">US15322008A 2016-12-23</td>
<td align="left">US9802691B2</td>
</tr>
<tr class="even">
<td align="left">US15346251A 2016-11-08</td>
<td align="left">US15346251A 2016-11-08</td>
<td align="left">US9805273B1</td>
</tr>
</tbody>
</table>
<p>For each of these numbers we observe the following structure</p>
<ol style="list-style-type: decimal">
<li>A two letter country code such as US (United States) or KR (South Korea)</li>
<li>A numeric identifier that, for more recent years, may include the year e.g 2016578323 or 15263985</li>
<li>A letter or combination of a letter and a number such as A, A1, B1, B2, S or P denoting the Kind of document</li>
<li>The date in Year - Month - Day format (known as YYYY-MM-DD)</li>
</ol>
<p>It is important to note that the patent numbers that are retrieved from patent databases are not necessarily presented in the way they are stored. For example, the country code, the numeric identifier, the kind code and the date are often stored in separate columns and are then combined together. When working with different databases this can be reflected in spaces between the country code, the number and the kind code. In addition, the original entries on patent application forms often include forward slashes <code>/</code>. In some cases databases will present numbers containing the forward slash character and in others they will be deleted as the do not add to the distinctiveness of the identifier. Be aware that some patent databases, notable Derwent Innovation from Clarivate Analytics, add padding 000s in the middle of some patent numbers to make them uniform and may add the year field at the beginning of patent numbers. For this reason using patent numbers across different databases is not as straightforward as it might be. Slight variations in the format will be the most common reason that a patent number is found in one database but not in another.</p>
<div id="the-country-code" class="section level3">
<h3><span class="header-section-number">3.1.1</span> The country code</h3>
<p>The two letter country code denotes either the country of filing, the country of application or the publication country. For example, in Table <a href="patents.html#tab:numbers">3.1</a> above, KR201528901A was first filed as an application in South Korea and then in the United States (US15057264A) and then published as a patent grant (US9807364B2) in the United States. A full list of two letter country codes, including the codes for the Patent Cooperation Treaty (WO) and regional instruments is available in the <a href="http://www.wipo.int/export/sites/www/standards/en/pdf/03-03-01.pdf">WIPO Handbook on Industrial Property Information and Documentation under standard ST.3 Recommended Standard on two-letter Codes for the Representation of States, Other Entities and Intergovernmental Organizations</a>. The same table is also available on <a href="https://en.wikipedia.org/wiki/WIPO_ST.3">Wikipedia</a>. Software tools such as VantagePoint provide thesaurii that will convert country codes to country names. </p>
<p>The country codes tell us where a document is filed and published. This provides the foundation for identifying trends by country using a range of different counts and for geographic mapping.</p>
</div>
<div id="the-numeric-identifier" class="section level3">
<h3><span class="header-section-number">3.1.2</span> The numeric identifier</h3>
<p>The second element of a patent number is a numeric identifier. As noted above, it is important to note that these identifiers may be edited by databases. For example, the Derwent World Patent Index often uses either a single or padding zero between the year in a field and the number. This probably arose from an effort to make patent numbers a uniform length but has the effect that these documents cannot easily be retrieved from databases that do not use padding zeros (such as <a href="mailto:esp@cenet">esp@cenet</a>). In other cases the numbers may include characters such as “/” that are not formally speaking part of the identifier. The kind code may also be added in some databases but not in others.</p>
<!--- provide a simple example here --->
</div>
<div id="kind-codes" class="section level3">
<h3><span class="header-section-number">3.1.3</span> Kind Codes</h3>
<p>Kind Codes appear as letter and number combinations after the numeric identifier. Kind codes describe the type of document and the publication level. Kind codes are documented in WIPO Standard <a href="http://www.wipo.int/patentscope/en/data/kind_codes.html">ST.16 Recommended Standard Code for the Identification of Different Kinds of Patent Documents</a>. Formally speaking Kind Codes are applied to:</p>
<blockquote>
<p>“patents for invention, inventors’ certificates, medicament patents, plant patents, design patents, utility certificates, utility models, patents or certificates of addition, utility certificates of addition, and published applications therefor” (WIPO ST.16 page 3.16.1, October 2016)</p>
</blockquote>
<p>In connection with the publication level, the definition explains that:</p>
<blockquote>
<p>“a “publication level” is defined as the level corresponding to a procedural stage at which normally a document is published under a given national industrial property law or under a regional or international industrial property convention or treaty&quot;</p>
</blockquote>
<p>So, to take a common example, a patent document may be published at the application stage. This is commonly the first procedural stage and is the first publication level. In many countries standard patent applications will receive the kind code A at this first publication level. In many countries, when a patent is granted the document enters the second publication level and it is published with kind code B. Other types of patent documents commonly receive their own kind codes denoting their type. For example Utility Models receive the kind code U while design patents received kind code S.</p>
<p>Kind codes are often accompanied by a number that adds additional information about the type of document. Within the WIPO standard these numbers range from 1 to 7 with numbers 8 and 9 reserved for corrections to the bibliographic data (e.g. A8) or to any part of the document (e.g. A9). WIPO <a href="http://www.wipo.int/standards/en/pdf/07-03-01.pdf">Examples and Kinds of Patent Documents</a> forms part of the WIPO Handbook on Industrial Property Information and Documentation setting out common Kind Codes and is recommended reading for patent analysts. Quick reference tables are also produced by Clarivate Analytics and national patent offices and are available online.</p>
<p>The use of patent kind codes has evolved over time and this can make accurate interpretation of a kind code difficult. In practice:</p>
<ol style="list-style-type: lower-alpha">
<li>The use of a kind code may vary in the same country over time. For example in the United States prior to 2001 patents were only published when they were granted (first publication level) and they were awarded kind code A. From 2001 onwards the United States adopted common practice elsewhere and published applications which now receive kind code A (as the first publication level) while patent grants are now the second publication level (and receive kind code B);</li>
<li>The use of kind codes varies between countries.</li>
</ol>
<p>As a very rough rule of thumb, publications with kind code A commonly mean the publication of an application. Publications with kind code B mean publication of a patent grant. But, this is not always true and it can only be described as a rough rule of thumb. This rule can normally be used when working with data from the main jurisdictions such as the United States (bearing in mind the pre and post 2001 changes considered below), the European Patent Office and the Patent Cooperation Treaty (which only covers first level publications or applications) and Japan. However, when working with country level data to elaborate trends for applications and grants it is important to review the use of kind codes in each country to be covered and to identify changes in the use of kind codes over time. When developing data on statistical trends for applications and grants a note should normally be added to inform readers that the data is approximate in cases where the use of kind codes has not been thoroughly explored and documented.</p>
<p>Patent kind codes denoting publication level and the kind of document (e.g. U) are important for statistical purposes because they allows for the identification of duplicates and, depending on the purpose of the analysis, the removal of unwanted data types (such as Utility models, design patents and plant patents) or the isolation of specific types of document. For most purposes kind codes are important for identifying patent applications and grants and critically for identifying republications of the same document (duplicates)</p>
<p>The most common kind codes encountered in patent data are:</p>
<p>First publication level (commonly but not exclusively patent applications)</p>
<ul>
<li>A1</li>
<li>A2</li>
<li>A3</li>
</ul>
<p>Second publication level (commonly but not exclusively patent grants)</p>
<ul>
<li>B1</li>
<li>B2</li>
<li>B3</li>
</ul>
<p>This means, to take a fictional example from the USPTO and its <a href="https://www.uspto.gov/learning-and-resources/support-centers/electronic-business-center/kind-codes-included-uspto-patent">common kind codes</a>, that:</p>
<ul>
<li>US1234A1 Patent Application Publication</li>
<li>US1234A2 Patent Application Publication (Republication)</li>
<li>US1234A9 Patent Application Publication (Corrected Publication)</li>
<li>US1234B1 Granted Patent (no previously published as a patent application)</li>
<li>US1234B2 Granted Patent (previously published as a patent application)</li>
</ul>
<p>In this example we have 3 potential publications of the same application and one publication of a patent grant (although corrections to a granted patent are possible). For the purpose of counting patent data how we deal with these republications or duplicates depends on the question we are trying to answer.</p>
<p>If we wanted to identify the priority application that is closest to the investment in research and development we would choose the earliest application number available to us (that may or may not have been published). In other cases we may want to count all applications that stem from a first filing or set of filings while in others we may want to identify applications and grants but remove administrative republications (simple republications and corrections or publication of the international search report) from the counts.</p>
<p>The main issue that arises here is determining what we wish to include and exclude from counts. One general approach to this issue is to simply <em>remove all republications of the same document (count the document only once on the earliest in the series)</em> . For example, if we were interested in counting patent applications and patent grants in the United States we would count US1234A1 and we would count the patent grant (US1234B2) and exclude the republications of the application. If we are only interested in counting patent applications we might simply remove the kind code denoting the different publication levels to count document US1234 only one. In practice, basic patent statistics commonly involves the use of multiple counting methods as we will see in more detail below.</p>
<p>As the discussion above makes clear when working with patent data to elaborate patent counts we must address <em>multiplier effects</em>. These take two main forms:</p>
<ol style="list-style-type: decimal">
<li>Republication of the same basic document in the same jurisdiction as applications, grants, or with modifications as continuations, continuations in part or divisionals.</li>
<li>Submission of applications under regional patent instruments or the Patent Cooperation Treaty (WO) and their republication as applications, grants, other administrative publications or divisionals (in relevant jurisdictions).</li>
</ol>
<p>Thus, under the Patent Cooperation Treaty an applicant may submit the same patent application for consideration in up to 152 Contracting States. In practice this is rare but in theory a single application could potentially lead to the republication of the same document as an application and grant 304 times (assuming a single publication of an application and the publication of a grant in each country). While this would be a very unusual case, it reveals the potential multiplier effects in patent counts introduced by regional instruments such as the European Patent Convention and the Patent Cooperation Treaty. As we will see below, in some cases a single document may be linked to over 1000 publications.</p>
</div>
</div>
<div id="preparing-to-count-patent-data" class="section level2">
<h2><span class="header-section-number">3.2</span> Preparing to Count Patent Data</h2>
<p>The patent identifiers discussed above provide the key for tracking patent documents around the world, using the concept of patent families discussed below, and for elaborating patent counts. The most important single piece of information when thinking about patent counts using identifiers is that patent patent data involves multiplier effects that leads often leads to the duplication or republication of the same document or a document that has been modified based on an earlier version.</p>
<p>Patent identifiers provide the basis for navigating these multiplier effects and the basis of patent counts commonly consists of removing duplicates or deduplication at different levels or combining documents in a variety of ways.</p>
<p>We will use the drones dataset as an example of this. Table <a href="patents.html#tab:dronenumbers">3.2</a> shows a sample of different patent numbers.</p>
<table>
<caption><span id="tab:dronenumbers">Table 3.2: </span>Priority, Applications, Publication and INPADOC Family Members</caption>
<thead>
<tr class="header">
<th align="left">priority_number</th>
<th align="left">application_number</th>
<th align="left">publication_number</th>
<th align="left">inpadoc_family_members</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">US2016578323F 2016-09-20</td>
<td align="left">US2016578323F 2016-09-20</td>
<td align="left">USD801224S1</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">US15360203A 2016-11-23</td>
<td align="left">US15360203A 2016-11-23</td>
<td align="left">US9807726B1</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">US62133061P 2015-03-13</td>
<td align="left">US15069675A 2016-03-14</td>
<td align="left">US9804596B1</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">US14622134A 2015-02-13</td>
<td align="left">US14622134A 2015-02-13</td>
<td align="left">US9802728B1</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">JP2015122335A 2015-06-17; WO2016JP67809A 2016-06-15</td>
<td align="left">US15322008A 2016-12-23</td>
<td align="left">US9802691B2</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
<p>We can see here that one or more priority numbers are linked to application numbers. In some cases those numbers are identical while in other cases they will be distinct. The application number is linked to one or more publication numbers. Patent databases commonly return data based on publication numbers. However, this is often only a partial picture of the set of documents linked to an application or set of applications and their underlying priority filings.</p>
<p>In the fifth example in Table <a href="patents.html#tab:dronenumbers">3.2</a> we can see that we have one publication number. However, we can see that under the INPADOC Family Member Number there are multiple patent publications that are not captured in the publication number field. There are two reasons for this.</p>
<ol style="list-style-type: lower-alpha">
<li>A search of a patent database commonly returns patent publications based on criteria such as limiting the search by jurisdiction. This does not reveal all documents linked to a filing or set of filings worldwide.</li>
<li>The INPADOC Family Members column groups publications based on a particular definition of a patent family. The number of documents will vary here depending on the definition of the patent family used in the data and whether the documents are deduplicated.</li>
</ol>
<p>Table <a href="patents.html#tab:countsummary">3.3</a> summarises the data by showing the counts of the different types of documents.</p>
<table>
<caption><span id="tab:countsummary">Table 3.3: </span>Sample of Patent Counts linked to the earliest priority number</caption>
<thead>
<tr class="header">
<th align="left">earliest_priority</th>
<th align="right">priority_count</th>
<th align="right">application_count</th>
<th align="right">family_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">US2016620248F 2016-09-02</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">US14835329A 2015-08-25</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">US15174819A 2016-06-06</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">US2013898275P 2013-10-31</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">US2015274112P 2015-12-31</td>
<td align="right">8</td>
<td align="right">18</td>
<td align="right">28</td>
</tr>
<tr class="even">
<td align="left">US201476360P 2014-11-06</td>
<td align="right">7</td>
<td align="right">4</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
<p>Table <a href="patents.html#tab:countsummary">3.3</a> helps to make clear that we may be dealing with simple cases (one priority or first filing) leads to one application and one family member. Or, we may be dealing with a group of priorities leading to multiple applications and multiple family members. This helps to clarify that, when working with patent data we are often dealing with <em>many to many relationships</em></p>
<p>In the next section we will progressively move up from counting patent documents using priority numbers and finish by using counts of INPADOC family members to elucidate trends for drone related technology.</p>
</div>
<div id="counting-priority-or-first-filings" class="section level2">
<h2><span class="header-section-number">3.3</span> Counting Priority or First Filings</h2>
<p>When a patent application is filed for the first time anywhere in the world it becomes the priority document or first filing. The use of this term is based on the 1883 Paris Convention. The WIPO summary of the key provisions of the Paris Convention explains the right of priority introduced by the Convention as follows.</p>
<blockquote>
<p>The Convention provides for the right of priority in the case of patents (and utility models where they exist), marks and industrial designs. This right means that, on the basis of a regular first application filed in one of the Contracting States, the applicant may, within a certain period of time (12 months for patents and utility models; 6 months for industrial designs and marks), apply for protection in any of the other Contracting States. These subsequent applications will be regarded as if they had been filed on the same day as the first application. In other words, they will have priority (hence the expression “right of priority”) over applications filed by others during the said period of time for the same invention, utility model, mark or industrial design. Moreover, these subsequent applications, being based on the first application, will not be affected by any event that takes place in the interval, such as the publication of an invention or the sale of articles bearing a mark or incorporating an industrial design. One of the great practical advantages of this provision is that applicants seeking protection in several countries are not required to present all of their applications at the same time but have 6 or 12 months to decide in which countries they wish to seek protection, and to organize with due care the steps necessary for securing protection.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a></p>
</blockquote>
<p>The OECD Manual on Patent Statistics describes the priority number and the priority date as follows</p>
<blockquote>
<p>Priority number. This is the application or publication number of the priority application, if applicable. It makes it possible to identify the priority country, reconstruct patent families, etc.</p>
</blockquote>
<blockquote>
<p>Priority date. This is the first date of filing of a patent application, anywhere in the world (usually in the applicant’s domestic patent office), to protect an invention. It is the closest to the date of invention. (OECD 2009: 25)</p>
</blockquote>
<p>The most important issue here from the perspective of patent counts is the priority date. Table <a href="patents.html#tab:countsummary">3.3</a> above revealed that patent applications may be linked to multiple underlying priority applications. The earliest filing, as shown in Table <a href="patents.html#tab:countsummary">3.3</a>, is the Paris priority in the sense that it is the first of a set of filings giving rise to a claimed invention.</p>
<p>In the simple cases as shown in the first, second and fourth entries of Table <a href="patents.html#tab:dronenumbers">3.2</a>, the priority number and the application number are the same. Therefore we have identified the priority or first filing. However, there are two other cases in Table <a href="patents.html#tab:dronenumbers">3.2</a>. The fifth example shown in Table <a href="patents.html#tab:jpwo">3.4</a> reveals a common case where a national level filing gives rise to an international filing under the Patent Cooperation Treaty.</p>
<p><strong>1. National Filing to International Filing</strong></p>
<p>First let’s look at the example in Table <a href="patents.html#tab:dronenumbers">3.2</a></p>
<table>
<caption><span id="tab:jpwo">Table 3.4: </span>Priority, Applications, Publication and INPADOC Family Members</caption>
<thead>
<tr class="header">
<th align="left">priority_number</th>
<th align="left">application_number</th>
<th align="left">publication_number</th>
<th align="left">inpadoc_family_members</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">US2016578323F 2016-09-20</td>
<td align="left">US2016578323F 2016-09-20</td>
<td align="left">USD801224S1</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">US15360203A 2016-11-23</td>
<td align="left">US15360203A 2016-11-23</td>
<td align="left">US9807726B1</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">US62133061P 2015-03-13</td>
<td align="left">US15069675A 2016-03-14</td>
<td align="left">US9804596B1</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">US14622134A 2015-02-13</td>
<td align="left">US14622134A 2015-02-13</td>
<td align="left">US9802728B1</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">JP2015122335A 2015-06-17; WO2016JP67809A 2016-06-15</td>
<td align="left">US15322008A 2016-12-23</td>
<td align="left">US9802691B2</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
<p><code>JP2015122335A 2015-06-17</code> is for a <code>Floating Type Flying Body</code>. We can see in row 5 that <code>JP2015122335A 2015-06-17</code> lists a second priority number for a Patent Cooperation Treaty filing <code>WO2016JP67809A 2016-06-15</code> . At first sight this leads to US patent application <code>US15322008A 2016-12-23</code> that is published as <code>US9802691B2</code>. However, when working with priority numbers we commonly encounter multiple applications arising from the priorities. Table <a href="patents.html#tab:jpwo1">3.5</a> displays counts of the priorities and applications linked to <code>JP2015122335A 2015-06-17</code> for a <code>Buoyant Aerial Vehicle</code></p>
<table>
<caption><span id="tab:jpwo1">Table 3.5: </span>Applications arising from JP2015122335A 2015-06-17</caption>
<thead>
<tr class="header">
<th align="left">earliest_priority</th>
<th align="right">priority_count</th>
<th align="right">application_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">JP2015122335A 2015-06-17</td>
<td align="right">2</td>
<td align="right">4</td>
</tr>
</tbody>
</table>
<p>The second priority number is the Patent Cooperation Treaty <code>WO2016JP67809A 2016-06-15</code>.</p>
<p>Table <a href="patents.html#tab:jpwo2">3.6</a> shows the sequence of applications arising from the the two priorities and the INPADOC patent family.</p>
<table>
<caption><span id="tab:jpwo2">Table 3.6: </span>Patent Applications arising from JP2015122335A with PCT application WO2016JP67809A</caption>
<thead>
<tr class="header">
<th align="left">priority_number</th>
<th align="left">application_number</th>
<th align="left">publication_number</th>
<th align="left">inpadoc_family_members</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">JP2015122335A 2015-06-17</td>
<td align="left">US15322008A 2016-12-23</td>
<td align="left">US9802691B2</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">JP2015122335A 2015-06-17</td>
<td align="left">EP2016811654A 2016-06-15</td>
<td align="left">EP3150483A1</td>
<td align="left">EP3150483A1 20170405; EP3150483A4 20170920; JP05875093B1 20160302; JP2017007411A 20170112; US20170137104A1 20170518; WO2016204180A1 20161222</td>
</tr>
<tr class="odd">
<td align="left">JP2015122335A 2015-06-17</td>
<td align="left">WO2016JP67809A 2016-06-15</td>
<td align="left">WO2016204180A1</td>
<td align="left">EP3150483A1 20170405; EP3150483A4 20170920; JP05875093B1 20160302; JP2017007411A 20170112; US20170137104A1 20170518; WO2016204180A1 20161222</td>
</tr>
<tr class="even">
<td align="left">JP2015122335A 2015-06-17</td>
<td align="left">JP2015122335A 2015-06-17</td>
<td align="left">JP05875093B1</td>
<td align="left">EP3150483A1 20170405; EP3150483A4 20170920; JP05875093B1 20160302; JP2017007411A 20170112; US20170137104A1 20170518; WO2016204180A1 20161222</td>
</tr>
</tbody>
</table>
<p>The first point to note is that Japanese priority application <code>JP2015122335A 2015-06-17</code> becomes application JP2015122335A 2015-06-17 and is then published as a patent application in Japan as <code>JP2017007411A 20170112</code> in January 2017 (first publication level) and also as a granted patent <code>JP05875093B1 20160302</code>.<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a></p>
<p>However, the Patent Cooperation Treaty application <code>WO2016JP67809A 2016-06-15</code> filed a year later triggers applications (on the same date) in the United States and at the European Patent Office.</p>
<p>Application number <code>US15322008A 2016-12-23</code> is published in May 2017 as <code>US20170137104A1 20170518</code> (first publication level) and on the second publication level as <code>US9802691B2</code>.</p>
<p>European application <code>EP2016811654A 2016-06-15</code> is published as <code>EP3150483A1 20170405</code> (first publication level with the search report) and as <code>EP3150483A4 20170920</code> with a supplementary search report.</p>
<p>Note here that the database entry for the inpadoc family members for the United States application is blank (NA stands for Not Available) indicating that this record had not been updated or correctly updated. An up to date view of the patent family is available from <a href="mailto:esp@cenet">esp@cenet</a> and includes the US records and more recent patent activity.</p>
<p>The priority data in this case reflects the decision taken by the applicant on the filing route to pursue protection in other countries in this case the United States using the Patent Cooperation Treaty. The Patent Cooperation Treaty has the advantage of extending the time that applicants enjoy before deciding where else to pursue protection from 12 months under the Paris Convention to up to 30 months [CROSS CHECK AND REF]. Applicants also enjoy reduced costs compared with the Paris Convention because a single application is submitted that may then go forward for consideration in other Contracting States.</p>
<p>Note that the filing route can be detected in the priority number <code>WO2016JP67809A 2016-06-15</code> which contains the country code JP as part of the application number. It is commonly the case that the listing of priorities numbers follows a sequence where the first priority number listed on a document is the earliest, followed by later applications.<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a></p>
<p>As this example makes clear when working with patent data we are typically following a pattern consisting of:</p>
<blockquote>
<p>priority number (earliest) &gt; application number &gt; publications (under different family definitions)</p>
</blockquote>
<p>At each step the publications associated with the original filings multiply.</p>
<p>In this case we are observing the <em>distinctive filing route</em> arising from a single priority filing. The filing route has nothing to do with the invention <em>per se</em>. However a more complex example reveals that inventions may arise from multiple claimed inventions.</p>
<p><strong>2. Multiple Inventions</strong></p>
<p>We have seen above that in some cases patent applications involve multiple priority numbers. Most will follow the pattern identified above. However, in some technology areas, notably those involving computing, multiple priority numbers may be quite common. In the case of the drones dataset a single application <code>US14815121A 2015-07-31</code> lists no less that 146 priorities and has given rise, at the time of writing, to an INPADOC patent family consisting of 340 publications. This example concerns a <code>Wireless Power System for an Electronic Display with Associated Impedence Matching Network</code>. It can be identified in <a href="mailto:esp@cenet">esp@cenet</a> using publication number <code>US2015357831A1</code> and a summary is presented in Table <a href="patents.html#tab:witricitysource">3.7</a>.</p>
<table>
<caption><span id="tab:witricitysource">Table 3.7: </span>Multiple Priorities and US Provisional and Continuation Filings</caption>
<thead>
<tr class="header">
<th align="left">priority_country</th>
<th align="right">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">AU</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">TW</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="left">US</td>
<td align="right">144</td>
</tr>
</tbody>
</table>
<p>Table <a href="patents.html#tab:witricitysource">3.7</a> reveals that the majority of priorities are domestic US priorities (144) with two foreign priorities in the form of Australia (1) and Taiwan.</p>
<p>The earliest priority filing listed in the set of priorities is <code>US2007647705A 2007-12-28</code> and the latest are in 2017 signifying that the underlying filings linked to this application spanned nearly a decade. Of the 143 priorities linked to the application originating from the United States 107 carry kind code A and 36 contain kind code P for a Provisional application. This therefore appears to be a case dominated by so called continuation and continuation in part, divisional and provisional applications.</p>
<p>In the United States applicants are allowed to file continuation and continuation in part applications. In the case of continuations the applicant adds new claims that claim priority to the earlier filed application. In the case of continuation in part, these applications add new subject matter focusing on enhancements to the original application. Divisional applications claim priority to the original application but claim distinct new inventions rather than adding new claims or subject matter. In the United States and elsewhere divisional applications often arise where the examiner determines that an application contains more than one invention. Provisional applications are a distinct category whereby an applicant for patent rights in the United States may submit and claim priority to what is effectively an outline of a full application that does not contain patent claims. These applications are useful for establishing priority but do not take effect until an actual application is filed and they are not published. Details of the procedures for these types of patent applications are found in the USPTO “Manual of Patent Examining Procedure (MPEP)”.</p>
<p>The use of continuation and continuation in part applications in the United States has been a significant focus of debate and criticism <span class="citation">(Hegde, Mowery, and Graham <a href="#ref-Hegde_2007">2007</a>)</span>. As Dechezlepretre et. al. have recently highlighted:</p>
<blockquote>
<p>“At the national or regional levels, applicants can in turn use second domestic filings, including divisional and continuing applications, to delay a patent grant. By filing a di- visional application while the parent application is still pending, applicants can obtain a second (or possibly more) divisional patent(s) granted later, and meanwhile maintain some uncertainty on the claims. In the U.S. patent system, continuations and continuations-in- part can be filed after the examination, and aim precisely at adding more claims to a patent (Hegde et al. 2009). Filing a first application with narrow claims thus makes it possible for the applicant to obtain several patents on the same invention, thereby gradually extending the overall scope of the claims and even, in the case of continuations-in-part, the duration of the patent family.” <span class="citation">(Dechezleprêtre, Ménière, and Mohnen <a href="#ref-Dechezleprêtre_2017">2017</a>, at 802)</span></p>
</blockquote>
<p>From the perspective of patent counts the question that arises here is what should be counted? Having gained an understanding of some of the potential issues involved in preparing to count patent data we now turn to methods for counting priority applications</p>
</div>
<div id="counting-priority-applications" class="section level2">
<h2><span class="header-section-number">3.4</span> Counting Priority Applications</h2>
<p>Counts of priority filings are widely used in patent statistics and economic analysis because they focus attention on the relationship between the filing of an application for an invention and the underlying investment in Research and Development leading to the invention. Viewed from this perspective, and as highlighted in the OECD Patent Statistics Manual, the earliest filing of a patent application provides a proxy indicator for investments in Research and Development in a particular technology area. This information can therefore be used as a basis for identifying and exploring trends.</p>
<p>Within the economics literature the preference therefore is for identifying and counting the earliest priority filing in a set of priorities. This is the approach that we will adopt here. However, the discussion of the Witricity case above involving multiple filings also reveals that we should be aware of some of the potential limitations of that approach. Thus, as mentioned above the priority filing of a patent application normally corresponds with the identical application number in the priority field. However, in the Witricity case the earliest filing was listed in December 2007 while the application was in mid 2015 roughly 7 years after the original filing. This raises the question of whether the date corresponding with the specific claimed invention should be taken or whether the earliest date should be taken as the basis for the proxy indicator.</p>
<p>In practice, in methodological terms it is easiest to identify the earliest priority in a set as the basis for elucidating trends in priority filings. However, this type of issue helps to illustrate that counts of priority filings are a proxy for underlying investments in Research and Development or in formal terms an <em>output indicator</em> and depending on your needs may merit refinement to more closely match the required granularity.</p>
<p>Counting patent filings by priority involves x basic steps</p>
<ol style="list-style-type: decimal">
<li>Checking the priority field for missing priority data (we can’t count missing data)</li>
<li>Separating out the concatenated column containing priority numbers. These numbers are commonly separated with a semi-colon.</li>
<li>Removing extra white space that is revealed by the separation process</li>
<li>Separating out the priority number and the priority date (commonly using the space between these fields)</li>
<li>Grouping the priority numbers by the application number and rank them from 1 to x with 1 being the earliest</li>
<li>Filter the priority numbers to the earliest (rank 1)</li>
<li>Detect duplicate priority numbers arising from those that share application numbers in the source set and remove them</li>
<li>Graph the results</li>
</ol>
<p>The methodological steps required for this task can be performed using tools such as Open Refine which can easily separate out the data or in VantagePoint. The key challenge is in grouping and ranking the priority numbers by the earliest data. This is most easily achieved using a programming language (such as an SQL GROUP BY, PARTITION BY and RANK) or in a language such as Python or R. In the case of R this can be achieved in the following lines of code. The code is commented to show the steps identified above.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">earliest_priority &lt;-<span class="st"> </span>numbers <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4-2" data-line-number="2"><span class="st">  </span><span class="kw">select</span>(priority_number, application_number) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb4-3" data-line-number="3"><span class="st">  </span><span class="kw">drop_na</span>(priority_number) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># drop empty priority fields</span></a>
<a class="sourceLine" id="cb4-4" data-line-number="4"><span class="st">  </span><span class="kw">separate_rows</span>(priority_number, <span class="dt">sep =</span> <span class="st">&quot;;&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># separate priority numbers on &quot;;&quot;</span></a>
<a class="sourceLine" id="cb4-5" data-line-number="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">priority_number =</span> <span class="kw">str_trim</span>(priority_number, <span class="dt">side =</span> <span class="st">&quot;both&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># trim whitespace</span></a>
<a class="sourceLine" id="cb4-6" data-line-number="6"><span class="st">  </span><span class="kw">separate</span>(priority_number, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;priority&quot;</span>, <span class="st">&quot;priority_date&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>, <span class="dt">remove =</span> <span class="ot">FALSE</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># extract the date </span></a>
<a class="sourceLine" id="cb4-7" data-line-number="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">priority_date =</span> lubridate<span class="op">::</span><span class="kw">ymd</span>(priority_date)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb4-8" data-line-number="8"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year =</span> lubridate<span class="op">::</span><span class="kw">year</span>(priority_date)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># add the priority year field</span></a>
<a class="sourceLine" id="cb4-9" data-line-number="9"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">priority_number =</span> <span class="kw">str_trim</span>(priority_number, <span class="dt">side =</span> <span class="st">&quot;both&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># trim whitespace</span></a>
<a class="sourceLine" id="cb4-10" data-line-number="10"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">priority_country =</span> <span class="kw">str_sub</span>(.<span class="op">$</span>priority_number, <span class="dv">1</span>,<span class="dv">2</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># extract the priority country</span></a>
<a class="sourceLine" id="cb4-11" data-line-number="11"><span class="st">  </span><span class="kw">group_by</span>(application_number) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># group by application number</span></a>
<a class="sourceLine" id="cb4-12" data-line-number="12"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">filing_order =</span> <span class="kw">rank</span>(priority_date, <span class="dt">ties.method =</span> <span class="st">&quot;first&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># rank by priority date </span></a>
<a class="sourceLine" id="cb4-13" data-line-number="13"><span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># remove grouping for later calculations</span></a>
<a class="sourceLine" id="cb4-14" data-line-number="14"><span class="st">  </span><span class="kw">filter</span>(filing_order <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># filter to the earliest priority at rank 1</span></a>
<a class="sourceLine" id="cb4-15" data-line-number="15"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">duplicate_priority =</span> <span class="kw">duplicated</span>(.<span class="op">$</span>priority_number)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># identify duplicate priority numbers</span></a>
<a class="sourceLine" id="cb4-16" data-line-number="16"><span class="st">  </span><span class="kw">filter</span>(duplicate_priority <span class="op">==</span><span class="st"> &quot;FALSE&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># remove duplicate priority numbers</span></a>
<a class="sourceLine" id="cb4-17" data-line-number="17"><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>priority) <span class="co"># drop uneccesary field</span></a></code></pre></div>
<p>While the above may appear initially appear complex it follows step 1 to 7 above. Because the data lacks a priority country and year field it extract these fields from the data to use in graphing as the next step. The key steps in arriving at accurate counts in the above process is trimming the separated fields to remove any leading and trailing white space. Note that the amount of cleaning required is likely to vary when working with data from different databases.</p>
<p>The steps above reduce the dataset from 15,776 applications containing 23,382 priority numbers (after the exclusion of Not Available results) to 9,358 earliest priority numbers.</p>
<p>We are now in a position to graph the data. For convenience we will continue to use R and the popular <code>ggplot2</code> package. The results of a raw count are presented in Figure <a href="patents.html#fig:priorityraw">3.1</a></p>
<div class="figure" style="text-align: center"><span id="fig:priorityraw"></span>
<img src="handbook2_files/figure-html/priorityraw-1.png" alt="Raw Graph of Trends in Priority Filings" width="672" />
<p class="caption">
Figure 3.1: Raw Graph of Trends in Priority Filings
</p>
</div>
<p>This is not generally what we will be expecting because it transpires that we have a long tail of low frequency records where the priority year is invalid such as <code>0001-01-01</code>, or the date was not in the expected YYYY-MM-DD. In addition this test dataset includes historic records from the 19th Century that we will not in this case be interested in seeing. It is therefore sensible to filter the results to a more recent period. Figure <a href="patents.html#fig:priorityraw1">3.2</a> shows the effect of filtering the priority year to 1990 to 2017.</p>
<div class="figure" style="text-align: center"><span id="fig:priorityraw1"></span>
<img src="handbook2_files/figure-html/priorityraw1-1.png" alt="Graph of Trends in Priority Filings showing the Priority Data Cliff" width="672" />
<p class="caption">
Figure 3.2: Graph of Trends in Priority Filings showing the Priority Data Cliff
</p>
</div>
<p>This version of the graph brings us closer but note that the data falls off a cliff between 2015 and 2017. This is a characteristic of counts of patents by priority filings and you should always expect to see it. The reason it occurs is not because of a collapse in patent activity but because of the lag time between the filing of applications and their availability as publications in patent databases. The gap between the filing of an application and its publication is generally 18 months but it may be at <em>least</em> two years. This problem is referred to as <code>timeliness</code> in patent statistics. The safest option is to pull back to the date range between 2 - 3 years to avoid giving the impression of a collapse in activity. Figure <a href="patents.html#fig:priorityraw2">3.3</a> shows the effect of this approach.</p>
<div class="figure" style="text-align: center"><span id="fig:priorityraw2"></span>
<img src="handbook2_files/figure-html/priorityraw2-1.png" alt="Graph of Trends in Priority Filings excluding the Data Cliff" width="672" />
<p class="caption">
Figure 3.3: Graph of Trends in Priority Filings excluding the Data Cliff
</p>
</div>
<p>More advanced techniques for addressing the problem of timeliness were developed by Helene Dernis at the OECD and subsequently taken forward by Eurostat <span class="citation">(Dernis <a href="#ref-Dernis_2007">2007</a>, de_Rassenfosse_2013)</span>.</p>
<p>The key advantage of counts of the earliest priority filings is that they remove the duplication that is inherent in patent data and allows us to focus in on the underlying filing rate: that is to examine trends in filings linked to underlying investments in Research and Development.</p>
<p>However, trends in the first filings of patent applications are not the whole story. Other types of patent counts focusing on applications, patent families and patent family members focus on the nature and geography of demand for patent rights.</p>
</div>
<div id="counting-applications" class="section level2">
<h2><span class="header-section-number">3.5</span> Counting Applications</h2>
<p>One challenge for the patent analyst is that data on priority applications may not be readily available or accessible when preparing a report. Patent databases vary in the quality of priority data and in these circumstances the use of simple counts of patent applications, accompanied by an explanatory note are likely to be an appropriate alternative. Here we need to bear in mind</p>
<ol style="list-style-type: lower-alpha">
<li>That we need to use the application year</li>
<li>That we will be counting distinct applications that may arise from the same underlying filing.</li>
</ol>
<p>Figure <a href="patents.html#fig:applnyr">3.4</a> shows trends in patent applications by application year.</p>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_path).</code></pre>
<div class="figure" style="text-align: center"><span id="fig:applnyr"></span>
<img src="handbook2_files/figure-html/applnyr-1.png" alt="Graph of Trends in Applications by Application Year" width="672" />
<p class="caption">
Figure 3.4: Graph of Trends in Applications by Application Year
</p>
</div>
<p>In this case the data cliff (not shown) occurs from 2016 onwards. This reflects the fact that when compared with counts by the earliest priority year, counts by application year <em>lean forward</em>. Because these counts also capture the applications stemming from a priority, such as applications in more than one country, they will also be at a higher level.</p>
<p>Figure <a href="patents.html#fig:priorappln">3.5</a> compares the two figures. Figure <a href="patents.html#fig:priorappln1">3.6</a> zooms in to the figure for the period 2005 to 2015.</p>
<div class="figure" style="text-align: center"><span id="fig:priorappln"></span>
<img src="handbook2_files/figure-html/priorappln-1.png" alt="Trends in First Filings and Patent Applications" width="672" />
<p class="caption">
Figure 3.5: Trends in First Filings and Patent Applications
</p>
</div>
<p>Figure <a href="patents.html#fig:priorappln1">3.6</a> focuses in on the period 2007 to 2015 to more clearly see the divergences between the data.</p>
<div class="figure" style="text-align: center"><span id="fig:priorappln1"></span>
<img src="handbook2_files/figure-html/priorappln1-1.png" alt="Trends in First Filings and Patent Applications" width="672" />
<p class="caption">
Figure 3.6: Trends in First Filings and Patent Applications
</p>
</div>
<p>As we might expect Figure <a href="patents.html#fig:priorappln">3.5</a> makes clear that counts of applications run parallel to trends in first filings. However, this is not the entire picture. Note the speed bump that appears between 2007 and 2010 starting with a downward inflexion in 2008 followed by an upward inflection and downward inflexion in 2010 reflecting a decrease then rapid increase and decrease in first filings. While the initial downward inflexion is displayed in the trend for applications the speed bump is replaced by a steadily increasing slope until 2013.</p>
<p>What this reflects is the follow on multiplier effect of applications based on the underlying filings being published in multiple jurisdictions that disguises the temporary bottoming out of first filings over the same period before growth in filings accelerates dramatically.</p>
<p>We can also see that in 2013 an inflexion occurs in filings and applications with the inflexion occurring at a higher document count for applications.</p>
<p>In summary, the application rate runs broadly in parallel with the priority rate <em>but</em> it smooths out and disguises changes in the priority filing rate that are likely to more closely reflect underlying investments in research and development.</p>
<div id="mapping-publications" class="section level3">
<h3><span class="header-section-number">3.5.1</span> Mapping Publications</h3>
<p>So far we have focused on mapping trends using the earliest priority documents and application numbers. We will now examine what happens if we map patent publications using the data contained in the inpadoc family member field consisting of 49,508 publications linked to the applications and their priorities. Figure <a href="patents.html#fig:family">3.7</a> shows the trend for counts of publications in the inpadoc family members field.</p>
<div class="figure" style="text-align: center"><span id="fig:family"></span>
<img src="handbook2_files/figure-html/family-1.png" alt="Trends in Publications (INPADOC Family Members)" width="672" />
<p class="caption">
Figure 3.7: Trends in Publications (INPADOC Family Members)
</p>
</div>
<p>We can now place this data which simply counts the number of publications within the INPADOC family members field into a graph with the counts by priority and applications as in Figure <a href="patents.html#fig:combined">3.8</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:combined"></span>
<img src="handbook2_files/figure-html/combined-1.png" alt="Trends in Publications (INPADOC Family Members)" width="672" />
<p class="caption">
Figure 3.8: Trends in Publications (INPADOC Family Members)
</p>
</div>
<p>We can see in Figure <a href="patents.html#fig:combined">3.8</a> that the difference between the patent publications linked to the applications and the first filings is dramatic. We will consider different definitions of patent families below. For the moment, the important observation here is that trends in the publication of INPADOC family members linked to the applications and priority filings do not closely match the pattern displayed by the applications and priority filings. What we are observing here is the multiplication effect of demand for patent rights in multiple countries around the world.</p>
<p>Demand for patent rights, as manifest in the filing, pursuit and maintenance of patent rights in multiple countries is an expression of the importance of the underlying invention to the applicants expressed in their willingness to pay for the pursuit of patent protection in different jurisdictions. Whereas first filings of patent applications are a proxy indicator for investments in research and development, trends in patent publications are an indicator of the commercial importance of those inventions to the applicants expressed in willingness to pay the relevant fees for examination of applications and the maintenance of patent grants. As we will see below the size of a patent family is therefore an indicator of the importance of an underlying invention to the applicant. However, as we will now see, while the majority of attention in patent statistics focuses on counts of priority filings and applications, publication data provides a route to identifying trends in patent applications and grants on the country and instrument level.</p>
<!--SHOULD A DISCUSSION AND TABLE OF PRIORITY COUNTRY, APPLICATION COUNTRY AND FAMILY COUNTRY GO HERE.







-->
</div>
</div>
<div id="trends-by-country-using-publication-data" class="section level2">
<h2><span class="header-section-number">3.6</span> Trends by Country using Publication Data</h2>
<p>In this section we illustrate the process for developing patent trends analysis at the country level using the drones data. However, it is important to emphasise that the drones dataset is not complete. A complete analysis would require the construction of a patent dataset that used searches for relevant jurisdictions in the appropriate languages using tools such as Patentscope CLIR (Cross Lingual Information Retrieval) which facilitates the translation of search terms into other languages. As such the drones data we will be working with is incomplete for national level analysis. However, bearing this major limitation in mind, it is nevertheless useful for illustrating methods, considering the issues that are likely to be encountered and how to deal with them.</p>
<p>When seeking to develop analysis on the country level it is important to note that some countries and instruments will display high levels of activity (WO, EP, US, JP, CN and others) while others will display very low levels of activity. As a consequence, attempts to graph the data will results in a large number of countries appearing at the bottom of the graph.</p>
<p>One approach to this is to simply focus on graphing the countries/instruments with the highest number of results. We will focus on mapping trends for the top countries and instruments. Figure <a href="patents.html#fig:pubtrends">3.9</a> displays the trends in publications, as an indicator of demand, for the top countries and instruments.</p>
<div class="figure" style="text-align: center"><span id="fig:pubtrends"></span>
<img src="handbook2_files/figure-html/pubtrends-1.png" alt="Trends in Publications using INPADOC Family data" width="672" />
<p class="caption">
Figure 3.9: Trends in Publications using INPADOC Family data
</p>
</div>
<p>Figure <a href="patents.html#fig:pubtrends">3.9</a> reveals that in terms of patent publication counts the United States is the lead country by a considerable margin, followed some distance behind by the PCT and the EPO. Note however, that this is not comparing like with like as the US data is confined to a single country whereas the EP and PCT are vehicles for the pursuit of protection in multiple countries.</p>
<p>We can also see that the dominance of the US data in terms of counts of publications is compressing the data for the other main countries and instruments to the bottom of the graph. In practice, the difference is so marked that we would probably seek to separate out the data. We will address this in greater detail below.</p>
<p>Patent publication data, in this case derived from INPADOC Family Member numbers is important because it allows for the analysis of trends in patent applications and patent grants using patent kind codes.</p>
<p>As discussed above, one challenge with patent kind codes that describe publication levels is that their use has varied over time. Thus in the United States prior to 2001 patent documents were only published when granted and received kind code A (first publication level). After 2001 the United States began publishing patent applications as the first publication level and they received kind code A while kind code B is used for the second publication level (granted patents).</p>
<p>This has two impacts on counts of patent data. First, as we see in Figure <a href="patents.html#fig:pubtrends">3.9</a> the data for the United States appears to leap between 2000 and 2001. This does not reflect a leap in patent activity but is instead a reporting effect arising from the publication of both applicants and grants. Second, we cannot simply use the A and B kind codes to separate out trends in patent applications and grants for the United States because they refer to different types of publications over time.</p>
<p>To address this we have created a field in the families table called <code>kind-adjusted</code> that has converted US kind code A documents to kind code B in the period before 2001. The original kind code is maintained in a field called <code>kind_original</code> as good practice when transforming the original data.</p>
<p>Figure <a href="patents.html#fig:ustrends">3.10</a> displays trends in patent applications and grants based on this adjustment.<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a></p>
<div class="figure" style="text-align: center"><span id="fig:ustrends"></span>
<img src="handbook2_files/figure-html/ustrends-1.png" alt="Trends in US Patent Applications and Grants" width="672" />
<p class="caption">
Figure 3.10: Trends in US Patent Applications and Grants
</p>
</div>
<p>These raw counts of publications with kind code A for applications and kind code B for patent grants reveal two points. In the case of this data there appears to have been a spike in patent grants between 2000 and 2001 from 67 to 184 grants which may, or may not, be associated with the shift to the publication of patent applications from 2001 onwards. The second point is that we observe the start of the publication of patent grants from 2001 onwards with notable peaks and troughs suggesting that this graph would benefit from smoothing. However, for our purposes we can clearly see the point at which US data is transformed in scale by the publication of applications. The important point to bear in mind here is that in the period prior to 2001, US patent activity was under-reported relative to activity elsewhere because only data on grants was published. From 2001 the US harmonises with the rest of the world and we see an apparent jump in activity that is in fact a reporting effect.</p>
<p>In considering the use of patent publication data (in this case arising from INPADOC family members) it is important to remember that data by publications also leans forward. Peaks and troughs in this data will in fact reflect changes in underlying filing activity from at least two years before. In addition, peaks and troughs will be affected by strategic behaviour by applicants such as the filing of continuation, continuation in part and divisional patent applications <span class="citation">(see Hegde, Mowery, and Graham <a href="#ref-Hegde_2007">2007</a> for discussion)</span> along with administrative issues within patent offices that may affect the publication of patent documents.</p>
<p>As this example suggests, significant caution is required when seeking to use publication data to map patent applications and grants in any given country. That is, it is important to investigate the use of kind codes over time for each country that is included in an analysis. For example, in a number of EPC member states, a regional European patent grant only becomes a national patent grant when it is translated. These documents are awarded kind code T. In EPC member states kind code T is therefore equivalent to a patent grant.</p>
<p>We will now look at trends across the top 10 countries. In doing so we need to recall the major caveat that this data will be incomplete for drone technology in each country. However, to get a feel for this we will start simply by mapping trends in publications and then break the data down using kind codes. Because some of the countries in the top ten have relatively limited activity we will include a loess smoothing trend line rather thank linking the data points. The results are presented in Figure <a href="patents.html#fig:familiescount">3.11</a> and limited to the period 2000-2017 for ease of visibility.</p>
<div class="figure" style="text-align: center"><span id="fig:familiescount"></span>
<img src="handbook2_files/figure-html/familiescount-1.png" alt="Publication Trends for Top Ten Countries (INPADOC Family Members)" width="672" />
<p class="caption">
Figure 3.11: Publication Trends for Top Ten Countries (INPADOC Family Members)
</p>
</div>
<p>In considering Figure <a href="patents.html#fig:familiescount">3.11</a> note that the scale of activity (shown by the y axis for each country) reveals quite dramatic differences in activity for each country. We can also see that Australia and Germany display unusual patterns. This type of pattern typically reflects a relative <em>lack of pattern</em> in low frequency data. As such, this type of graph can assist with decision making in identifying the most significant sources of data to present to readers for analysis.</p>
<p>In work on the development of the scientific and patent landscape for marine genetic resources for South East Asian countries a problem emerged where major peaks were encountered followed by zero or very low activity. Radical peaks and troughs in patent data typically suggest <em>missing data</em>. In the case of South East Asia it transpired that PATSTAT had very limited coverage of ASEAN national collections and thus presented a very partial view when compared with Derwent Innovation which includes the ASEAN national collections. As such, graphs of the type displayed above should be initially used for exploratory data analysis with a focus on the assessment of the completeness of the data (in this case we know that the data will be incomplete).</p>
<p>Figure <a href="patents.html#fig:familiescount">3.11</a> also provides us with important clues on what we might expect when we seek to visualise patent trends by kind codes for these countries. That is we should expect to see erratic data or <em>no real pattern</em> for countries with lower counts. For illustration Figure <a href="patents.html#fig:familieskind">3.12</a> presents the breakout of the data for each country above using kind code A and B and excluding other types of document (e.g, Utility models and designs).</p>
<div class="figure" style="text-align: center"><span id="fig:familieskind"></span>
<img src="handbook2_files/figure-html/familieskind-1.png" alt="Publication Trends for Top Ten Countries with Kind Code A and B" width="672" />
<p class="caption">
Figure 3.12: Publication Trends for Top Ten Countries with Kind Code A and B
</p>
</div>
<p>A number of features emerge in Figure <a href="patents.html#fig:familieskind">3.12</a>, In the case of the PCT we can see a small number of patent documents with Kind Code B. In practice there are two PCT documents in the dataset with Kind Code B. This is presumably a data entry mistake because WIPO does not issue documents with Kind Code B as the PCT has no second publication level. A second feature emerges in the case of Japan where the number of patent applications dips dramatically below the level of B documents before increasing dramatically. We would reasonably expect that the application rate would be higher than the grant rate. In practice, this issue will reflect the incomplete nature of the dataset we are working with.</p>
<p>A third issue arises with Australia which exhibits a peak in activity around 2000/2001 and then collapses. One known issue with data from Australia is that around this period Australia recorded PCT designations as if they were actual applications leading to distortion of the statistics between approximately 2000 an 2003 [ref patstat forum].</p>
<p>In the case of Canada (CA) we observe activity for Kind code A but no activity for Kind code B. This illustrates the importance, as emphasised above, of examining the use of kind codes in individual countries that will be the focus for analysis. Canada uses Kind code C for patent grants while Kind Code B is used for reissue patents.</p>
<p>The case of China (CN) which displays data for kind code B from 2010 onwards may suggest that there are limitations in the availability of patent grant data that require investigation. In the case of Germany (DE) this exposes the limitations of our dataset (which did not involve searching the German collection). While bearing this in mind, note that the data on patent grants (which exceeds those for applications) is reflecting the translation of EPC patent grants. In practice the landscape of Kind Codes for Germany is quite complicated and once again reveals the need to review Kind Codes with considerable care when developing this type of analysis.</p>
</div>
<div id="patent-families" class="section level2">
<h2><span class="header-section-number">3.7</span> Patent Families</h2>
<p>In the preceding sections we have moved from counting patent data by priority or first filings, to counting applications and then using patent publications to explore the issues involved in mapping trends in patent applications and grants on the country level. As we have seen when we move to the country level issues of data capture from the search strategy and the interpretation of Kind Codes become major issues.</p>
<p>As part of this discussion we used patent publication data from INPADOC Family Members that are linked to the underlying first filings. We will now look at patent families and their uses in more detail.</p>
<p>At its simplest a patent family is simply a grouping of patent documents based on a relationship or set of relationships. As we will see below that relationship can vary. However, for everyday purposes the following working definition has the benefit of being simple and easy to remember.</p>
<blockquote>
<p>At its simplest a patent family can be understood as a stack of documents published in any language anywhere in the world that share a common parent in the form of a priority number.</p>
</blockquote>
<p>As we will see, this simple working definition describes around 75% of patent families in the PATSTAT database.</p>
<p>In practice, there are a number of different definitions of patent families.</p>
<ol style="list-style-type: decimal">
<li>Simple first filing based families. These are families where members must share a priority number <span class="citation">(Martinez <a href="#ref-Martinez_2010">2010</a><a href="#ref-Martinez_2010">a</a>)</span>.
2 <a href="https://www.epo.org/searching-for-patents/helpful-resources/first-time-here/patent-families/docdb.html">DOCDB families</a>. Similar to the above except that based on expert review at the EPO documents with the same technical content are added to the family. DOCDB refers to the EPO central documentation database <span class="citation">(Martinez <a href="#ref-Martinez_2010">2010</a><a href="#ref-Martinez_2010">a</a>)</span></li>
<li><a href="https://www.epo.org/searching-for-patents/helpful-resources/first-time-here/patent-families/inpadoc.html">INPADOC extended families</a>. These families share the DOCDB definition but the definition is expanded so if document A shares a priority number with document B they are in the same family. However, if document C shares a priority with document B but not document A then document C will still be grouped in the family of document A.<a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a> In addition, examiners may identify other technically related documents that are added to the family. INPADOC patent families are therefore larger than DOCDB simple families (see below).</li>
<li><a href="https://data.oecd.org/rd/triadic-patent-families.htm">Triadic patent families</a> (OECD definition for filings shared between the US, EP and JP). This is used by the OECD in patent analysis to refer to patent filings that are made in the United States, at the European Patent Office and in Japan. The aim of these families is to allow for analysis of the internationalisation of technology by neutralising the home bias created by the fact that most applications are made in national offices. This is achieved by focusing on those made at the three major offices <span class="citation">(Dernis and Khan <a href="#ref-Dernis_2004">2004</a>; Criscuolo <a href="#ref-Criscuolo_2006">2006</a>; Sternitzke <a href="#ref-Sternitzke_2009">2009</a>)</span>.</li>
<li><a href="https://wiki.piug.org/display/PIUG/Patent+Families">Derwent Patent families</a>. A type of patent family used in the Derwent World Patent Index from Clarivate Analytics. This type of patent family relies on the identification of new priority filings that become the Basic patent for a patent family. Documents sharing that priority are classified as equivalents and become part of the patent family and includes continuation and continuations in part. In addition, what are called non-convention equivalents that do not share a priority but with the same technical content are added to the family and marked. This allows users to identify documents for the same invention that do not share a priority.</li>
<li><a href="https://www.patbase.com/login.asp">PatBase</a> defines its families as follows: &quot;A PatBase family contains all publications that share one or more common priority number(s). This includes continuations-in-part. If PatBase families become very large (100+ members) where possible these are broken down into sub-groups of simple families. A simple family is one where all priority numbers are shared.</li>
</ol>
<p>It is likely that this list of definitions of patent families is incomplete but it indicates the range of possible groupings.</p>
<p>In practice, the most commonly encountered definitions of patent families are simple families, DOCDB families and INPADOC extended families.
However, as we can see from the definitions above one challenge with patent families is that there appears to be an element of subjective judgement whereby examiners or database providers take decisions on the members of patent families. In addition patent database providers do not always clearly describe the process for determining patent families. This can make patent families confusing and the simple working definition provided above is designed to give clarity of focus.</p>
<p>Research on patent families has been greatly enhanced by the creation in 2006 of the EPO World Patent Statistical Database (PATSTAT). In 2010 Catalina Martinez published an important OECD Working Paper entitled <em>Insight into Different Types of Patent Families&quot; on the structure of patent families using PATSTAT data for the period between 1991 and 2009</em> <span class="citation">(Martinez <a href="#ref-Martinez_2010">2010</a><a href="#ref-Martinez_2010">a</a>, <a href="#ref-Martinez_2010a">2010</a><a href="#ref-Martinez_2010a">b</a>)</span>. This study made a major contribution to clarifying the impact of different definitions of patent families using PATSTAT as an international baseline and also explored the structure of patent families. We will now briefly summarise and explore the main findings from this study.</p>
<p>Martinez focuses on the important question of how to build patent families and identifies four types of linkages that can be used to build patent families:</p>
<ol style="list-style-type: decimal">
<li>Paris Convention priorities</li>
<li>Technical similarities (also called non-convention priorities, intellectual priorities or technical relations)</li>
<li>Domestic priorities (e.g.continuations, continuations in part, provisionals, divisionals)</li>
<li>PCT regional/national phase entries (Martinez 2010: 23)</li>
</ol>
<p>Each of these types of linkages is accompanied by a definition and whether the information is provided by the applicant as in Table <a href="patents.html#tab:martineztab">3.8</a> reproduced from Martinez below (Martinez, 2010. Table 7, 23)</p>
<table>
<caption><span id="tab:martineztab">Table 3.8: </span>Sources of the Building Blocks for Patent Families</caption>
<thead>
<tr class="header">
<th align="left">Type</th>
<th align="left">Definition</th>
<th align="left">Claimed by applicant in patent document</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Paris Convention priorities</td>
<td align="left">Allow a one year delay between first original filing and subsequent foreign filings by same applicant claiming the priority right (1883 Paris Convention).</td>
<td align="left">YES</td>
</tr>
<tr class="even">
<td align="left">Technical similarities</td>
<td align="left">Relations among patent documents with similar scope, inventor and applicant names, that nevertheless lack common priority. An artificial priority link is assigned manually by the database producers.</td>
<td align="left">NO</td>
</tr>
<tr class="odd">
<td align="left">Domestic priorities</td>
<td align="left">Filed at the same office. They are mainly continuations, continuations in part and provisionals (the three of them only available at USPTO), and divisionals, which are available at most patent offices (1883 Paris Convention).</td>
<td align="left">YES</td>
</tr>
<tr class="even">
<td align="left">National phase entries of PCT filings</td>
<td align="left">Entry into regional/national phases of PCT filings.</td>
<td align="left">YES</td>
</tr>
</tbody>
</table>
<p>As we can see in this table, the source of information for building patent families predominantly comes from the applicant except for the technical similarities. Technical similarities are identified by examiners based on their assessment of the scope, inventor and applicant names and result in an artificial priority link. As such, the identification of technical similarities is not purely subjective.</p>
<p>Martinez then uses the EPO World Patent Statistical Database (PATSTAT) to quantify the impact of the use of the different linkages on the size of patent families for the period 1991 to 1999. Table <a href="patents.html#tab:martinezcounts">3.9</a> reproduces Table 9 from Martinez’s research.</p>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:martinezcounts">Table 3.9: </span>Counts of families and applications in them, by source of family relations 1991-1999 <span class="citation">(Martinez <a href="#ref-Martinez_2010">2010</a><a href="#ref-Martinez_2010">a</a>)</span>
</caption>
<thead>
<tr>
<th style="border-bottom:hidden" colspan="1">
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">
Source 1 Families
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">
Source 2 Families
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">
Source 3 Families
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">
Source 4 Families
</div>
</th>
</tr>
<tr>
<th style="border-bottom:hidden" colspan="1">
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">
Paris Convention
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">
Paris Convention + Domestic Continuations
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">
Paris Convention<br>+ Domestic continuations + Technical similarities)
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">
Paris Convention + Domestic continuations + Technical similarities + PCT national phase entries
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
year
</th>
<th style="text-align:right;">
families
</th>
<th style="text-align:right;">
members
</th>
<th style="text-align:right;">
families
</th>
<th style="text-align:right;">
members
</th>
<th style="text-align:right;">
families
</th>
<th style="text-align:right;">
members
</th>
<th style="text-align:right;">
families
</th>
<th style="text-align:right;">
members
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1991
</td>
<td style="text-align:right;">
106850
</td>
<td style="text-align:right;">
567024
</td>
<td style="text-align:right;">
110371
</td>
<td style="text-align:right;">
610367
</td>
<td style="text-align:right;">
110856
</td>
<td style="text-align:right;">
614631
</td>
<td style="text-align:right;">
110745
</td>
<td style="text-align:right;">
614888
</td>
</tr>
<tr>
<td style="text-align:left;">
1992
</td>
<td style="text-align:right;">
107873
</td>
<td style="text-align:right;">
571499
</td>
<td style="text-align:right;">
113659
</td>
<td style="text-align:right;">
624205
</td>
<td style="text-align:right;">
114394
</td>
<td style="text-align:right;">
629235
</td>
<td style="text-align:right;">
114276
</td>
<td style="text-align:right;">
629538
</td>
</tr>
<tr>
<td style="text-align:left;">
1993
</td>
<td style="text-align:right;">
112351
</td>
<td style="text-align:right;">
602058
</td>
<td style="text-align:right;">
119014
</td>
<td style="text-align:right;">
655380
</td>
<td style="text-align:right;">
119656
</td>
<td style="text-align:right;">
659896
</td>
<td style="text-align:right;">
119533
</td>
<td style="text-align:right;">
660106
</td>
</tr>
<tr>
<td style="text-align:left;">
1994
</td>
<td style="text-align:right;">
116602
</td>
<td style="text-align:right;">
639485
</td>
<td style="text-align:right;">
123818
</td>
<td style="text-align:right;">
693431
</td>
<td style="text-align:right;">
124606
</td>
<td style="text-align:right;">
698404
</td>
<td style="text-align:right;">
124362
</td>
<td style="text-align:right;">
699194
</td>
</tr>
<tr>
<td style="text-align:left;">
1995
</td>
<td style="text-align:right;">
129535
</td>
<td style="text-align:right;">
722318
</td>
<td style="text-align:right;">
135946
</td>
<td style="text-align:right;">
761371
</td>
<td style="text-align:right;">
136702
</td>
<td style="text-align:right;">
766020
</td>
<td style="text-align:right;">
136405
</td>
<td style="text-align:right;">
766939
</td>
</tr>
<tr>
<td style="text-align:left;">
1996
</td>
<td style="text-align:right;">
146281
</td>
<td style="text-align:right;">
805300
</td>
<td style="text-align:right;">
152088
</td>
<td style="text-align:right;">
849307
</td>
<td style="text-align:right;">
152994
</td>
<td style="text-align:right;">
854422
</td>
<td style="text-align:right;">
152681
</td>
<td style="text-align:right;">
855240
</td>
</tr>
<tr>
<td style="text-align:left;">
1997
</td>
<td style="text-align:right;">
161060
</td>
<td style="text-align:right;">
874480
</td>
<td style="text-align:right;">
166277
</td>
<td style="text-align:right;">
914281
</td>
<td style="text-align:right;">
167220
</td>
<td style="text-align:right;">
919518
</td>
<td style="text-align:right;">
166857
</td>
<td style="text-align:right;">
920284
</td>
</tr>
<tr>
<td style="text-align:left;">
1998
</td>
<td style="text-align:right;">
173243
</td>
<td style="text-align:right;">
939352
</td>
<td style="text-align:right;">
179345
</td>
<td style="text-align:right;">
985989
</td>
<td style="text-align:right;">
180095
</td>
<td style="text-align:right;">
990508
</td>
<td style="text-align:right;">
179618
</td>
<td style="text-align:right;">
990914
</td>
</tr>
<tr>
<td style="text-align:left;">
1999
</td>
<td style="text-align:right;">
196972
</td>
<td style="text-align:right;">
1057368
</td>
<td style="text-align:right;">
204330
</td>
<td style="text-align:right;">
1102833
</td>
<td style="text-align:right;">
205222
</td>
<td style="text-align:right;">
1106929
</td>
<td style="text-align:right;">
204659
</td>
<td style="text-align:right;">
1107482
</td>
</tr>
<tr>
<td style="text-align:left;">
1991-1999
</td>
<td style="text-align:right;">
1250767
</td>
<td style="text-align:right;">
6778884
</td>
<td style="text-align:right;">
1304848
</td>
<td style="text-align:right;">
7197164
</td>
<td style="text-align:right;">
1311745
</td>
<td style="text-align:right;">
7239563
</td>
<td style="text-align:right;">
1309136
</td>
<td style="text-align:right;">
7244585
</td>
</tr>
</tbody>
</table>
<p>Note that Table <a href="patents.html#tab:martinezcounts">3.9</a> focuses on the earliest priorities and excludes singletons.b</p>
<p>A number of important points emerge in Martinez’s analysis. The first of these is that “Paris Convention priorities alone make up more than 95%, which make them the most relevant patent linkage by far in the construction of extended patent families.” As such Paris Convention priorities are the foundation of patent families.</p>
<p>The second major observation is that the number and size of families increases as the definition is expanded in the first three cases. The third case exactly matches with the widely used INPADOC extended patent family definition (Paris, domestic continuations and technical similarities). However, observe that the number of <em>families</em> in the final case in the table is lower in all cases than for the source 3 (INPADOC) even while the number of family members increases. The reason for this is that first three types create new independent families. In contrast, the final type consolidates families by revealing shared links through the Patent Cooperation Treaty. That is, the number of families falls because otherwise hidden linkages with the PCT become obvious (see Martinez 2010: 25).</p>
<p>Using this data we can visualise the impact of different types of counts of families and family members. We will focus here on displaying the difference between the simple family definition and the INPADOC definition (source 3 above). Figure <a href="patents.html#fig:martinezfamilies">3.13</a> trends in the number of patent families using the simple and INPADOC definitions.</p>
<div class="figure" style="text-align: center"><span id="fig:martinezfamilies"></span>
<img src="handbook2_files/figure-html/martinezfamilies-1.png" alt="PATSTAT Trends in DOCDB Simple and INPADOC Extended Patent Families [@Martinez_2010]" width="672" />
<p class="caption">
Figure 3.13: PATSTAT Trends in DOCDB Simple and INPADOC Extended Patent Families <span class="citation">(Martinez <a href="#ref-Martinez_2010">2010</a><a href="#ref-Martinez_2010">a</a>)</span>
</p>
</div>
<p>We can see here that the DOCDB simple families and the INPADOC family counts follow the same pattern except that the number of inpadoc families are consistently larger than the DOCDB simple families.</p>
<p>Figure <a href="patents.html#fig:familiesandmembers">3.14</a> places counts of the families and family members onto the same graph the difference between counting the number of families rather than the number of family members comes into focus.</p>
<div class="figure" style="text-align: center"><span id="fig:familiesandmembers"></span>
<img src="handbook2_files/figure-html/familiesandmembers-1.png" alt="Trends in Patent Families (priority filings) and Family Members compared" width="672" />
<p class="caption">
Figure 3.14: Trends in Patent Families (priority filings) and Family Members compared
</p>
</div>
<p>In considering this graph note that while the families count range is in the hundreds of thousands, with 205,222 INPADOC families in 1999, the equivalent count for INAPDOC family members was 1,106,929. Under both definitions this brings home the scale of the multiplier effects arising from the publication and republication of patent documents. We have seen a similar type of pattern in Figure <a href="patents.html#fig:combined">3.8</a> for the drones data where the number of patent family members accelerates away from the priority filings as publications multiply.</p>
<p>Martinez also explores and quantifies the different structures of patent families in the period between 1991 and 1999 <span class="citation">(see in particular Martinez <a href="#ref-Martinez_2010">2010</a><a href="#ref-Martinez_2010">a</a>)</span>. Martinez developed an algorithm to assess the structure of the INPADOC patent families discussed above and found that:</p>
<blockquote>
<p>“Applying the algorithm just described to the 1 311 745 INPADOC extended patent families with earliest priorities in the 1990s, as reported in PATSTAT September 2008, and excluding families formed by one patent document only (singletons), a total of 47 437 different family structures are identified. Among them, however, only a few structures are really popular: 86% of the structures represent just one family each, whereas only 10 structures represent 73% of all families and 25 represent 81%. In addition, more than half of the top 25 structures are made up of one earliest priority followed by several direct subsequent filings, what we will call “simple structures” from now onwards.&quot;<a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a></p>
</blockquote>
<p>The important point here is that while initially the structure of patent families may appear to be extremely diverse, with 47,437 different family structures, in practice 10 structures described 73% of the families and 25 structures accounted for 81%. This is a very significant finding because it informs us that the majority of the time the structure of patent families falls within a limited set. Furthermore, of the top 25 structures, over half are made up of a simple structure consisting of a single earliest priority followed by several direct filings. Martinez goes on to conclude that “…we have found that 75% of all INPADOC extended priority patent families with earliest priorities between 1991 and 1999 have a simple structure, consisting of one single first filing and its direct subsequent filings” <span class="citation">(Martinez <a href="#ref-Martinez_2010">2010</a><a href="#ref-Martinez_2010">a</a>)</span>. The broader significance of this is because INPADOC extended families are the broadest category of common family types that 75% of other patent families will be of the single first filing and direct subsequent (child) filing type.</p>
<p>From this we can reasonably conclude that the majority of patent families that we will ever encounter will be of the simple type (single priority followed by several direct filings). However as Martinez also notes “Complex families may favor specific technologies, countries or more valuable patents” (Martinez 2010: 17) so it is important to bear in mind that complex families while representing a much smaller proportion of the data may also be important.</p>
<p>In considering the use of different types of family counts the most commonly encountered forms will be the DOCDB simple family types or the INPADOC family types. In the sections above we have graphed families (priority filings) and used raw family members to explore trends in different countries. However, as mentioned above the size of patent families is an indication of the importance of an invention to the applicants based on their willingness to pay fees for the stages of the procedure and for the maintenance of any granted patents in one or more jurisdiction. Table <a href="patents.html#tab:topfamily">3.10</a> displays the raw count of INPADOC family members across the drones dataset linked to the earliest priority number.</p>
<table>
<caption>
<span id="tab:topfamily">Table 3.10: </span>Top INPADOC Families
</caption>
<thead>
<tr>
<th style="text-align:left;">
earliest_priority
</th>
<th style="text-align:left;">
application_number
</th>
<th style="text-align:right;">
family_count
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
AU19977991A 1997-07-15
</td>
<td style="text-align:left;">
JP200944799A 2009-02-26
</td>
<td style="text-align:right;">
2964
</td>
</tr>
<tr>
<td style="text-align:left;">
US13420236A 2012-03-14
</td>
<td style="text-align:left;">
US14253376A 2014-04-15
</td>
<td style="text-align:right;">
1819
</td>
</tr>
<tr>
<td style="text-align:left;">
US2013811981P 2013-04-15
</td>
<td style="text-align:left;">
US14253099A 2014-04-15
</td>
<td style="text-align:right;">
1819
</td>
</tr>
<tr>
<td style="text-align:left;">
US2001270625P 2001-02-23
</td>
<td style="text-align:left;">
EP2002714961A 2002-02-21
</td>
<td style="text-align:right;">
1440
</td>
</tr>
<tr>
<td style="text-align:left;">
US2011452418P 2011-03-14
</td>
<td style="text-align:left;">
US14024204A 2013-09-11
</td>
<td style="text-align:right;">
808
</td>
</tr>
<tr>
<td style="text-align:left;">
US2002387792P 2002-06-11
</td>
<td style="text-align:left;">
US13602510A 2012-09-04
</td>
<td style="text-align:right;">
808
</td>
</tr>
<tr>
<td style="text-align:left;">
US14064189A 2013-10-27
</td>
<td style="text-align:left;">
US14526503A 2014-10-28
</td>
<td style="text-align:right;">
371
</td>
</tr>
<tr>
<td style="text-align:left;">
US13158372A 2011-06-10
</td>
<td style="text-align:left;">
US14065419A 2013-10-29
</td>
<td style="text-align:right;">
371
</td>
</tr>
<tr>
<td style="text-align:left;">
US201364189A 2013-10-27
</td>
<td style="text-align:left;">
EP2014857043A 2014-10-28
</td>
<td style="text-align:right;">
371
</td>
</tr>
<tr>
<td style="text-align:left;">
US14065415A 2013-10-28
</td>
<td style="text-align:left;">
WO2014US62477A 2014-10-27
</td>
<td style="text-align:right;">
371
</td>
</tr>
</tbody>
</table>
<!--drones related is publn US9033116B2 and appln US14024204A 2013-09-11-->
<p>The top result in the drones dataset lists an earliest priority filing in 1997 and concerns a <em>Methods for Manufacturing Inkjet Print Head using Multilayer Material Layer</em> by Silverbrook Research in Australia involving Kia Silverbrook who has been described on Wikipedia as having been the worlds most prolific inventor.<a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a> According to news reports Silverbrook Research went into administration in 2014.<a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a>.</p>
<p>This is an example of noise in our drones dataset and a historic example, however the size of the INPADOC patent family indicates that the claimed invention was of great importance to the applicants. Table <a href="patents.html#tab:topfamilycountry">3.11</a> displays the countries that have been the focus for the development of this family. Note that each document in the family is counted.</p>
<table>
<caption>
<span id="tab:topfamilycountry">Table 3.11: </span>Top Family Countries for priority AU19977991A
</caption>
<thead>
<tr>
<th style="text-align:left;">
family country
</th>
<th style="text-align:right;">
raw
</th>
<th style="text-align:right;">
consolidated
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
US
</td>
<td style="text-align:right;">
2116
</td>
<td style="text-align:right;">
2116
</td>
</tr>
<tr>
<td style="text-align:left;">
AU
</td>
<td style="text-align:right;">
334
</td>
<td style="text-align:right;">
292
</td>
</tr>
<tr>
<td style="text-align:left;">
SG
</td>
<td style="text-align:right;">
52
</td>
<td style="text-align:right;">
52
</td>
</tr>
<tr>
<td style="text-align:left;">
EP
</td>
<td style="text-align:right;">
119
</td>
<td style="text-align:right;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
JP
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
44
</td>
</tr>
<tr>
<td style="text-align:left;">
WO
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
38
</td>
</tr>
<tr>
<td style="text-align:left;">
CN
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
DE
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
31
</td>
</tr>
<tr>
<td style="text-align:left;">
IL
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
30
</td>
</tr>
<tr>
<td style="text-align:left;">
KR
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
30
</td>
</tr>
<tr>
<td style="text-align:left;">
AT
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
28
</td>
</tr>
<tr>
<td style="text-align:left;">
ZA
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
27
</td>
</tr>
<tr>
<td style="text-align:left;">
CA
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
26
</td>
</tr>
<tr>
<td style="text-align:left;">
NZ
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
ES
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<p>Table <a href="patents.html#tab:topfamilycountry">3.11</a> shows the raw counts of family member documents for each country and the consolidated counts (with the kind codes removed to group by document identifier). The documents are ranked on the count of the consolidated family members.</p>
<p>We can immediately see that while the applicant company was Australian the key target market was the United States followed by Australia, Singapore, Europe (through the European Patent Office) and Japan. By far the greatest intensity of family members is found in the United States and it transpires that these family members are clustered by date. Figure <a href="patents.html#fig:uscluster">3.15</a> shows US family member publications as a simple frequency plot over time.</p>
<div class="figure" style="text-align: center"><span id="fig:uscluster"></span>
<img src="handbook2_files/figure-html/uscluster-1.png" alt="Frequency Plot for the Publication of US Family Members for priority number AU19977991A 1997-07-15" width="672" />
<p class="caption">
Figure 3.15: Frequency Plot for the Publication of US Family Members for priority number AU19977991A 1997-07-15
</p>
</div>
<p>Figure <a href="patents.html#fig:uscluster">3.15</a> shows a strong clustering effect. In order to more clearly understand what is happening inside this plot Figure <a href="patents.html#fig:usclustergrants">3.16</a> displays the frequencies for US granted patents within the family over time (kind code B)</p>
<div class="figure" style="text-align: center"><span id="fig:usclustergrants"></span>
<img src="handbook2_files/figure-html/usclustergrants-1.png" alt="Frequency Plot for Patent Grants among US Family Members for priority number AU19977991A 1997-07-15" width="672" />
<p class="caption">
Figure 3.16: Frequency Plot for Patent Grants among US Family Members for priority number AU19977991A 1997-07-15
</p>
</div>
<p>What emerges here is that there are 1,086 US patent grants that can be traced to the single Australian priority filing.<a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a> The earliest US patent grant in the set was published in March 2000 as US6041600A
for the <code>Utilization of quantum wires in MEMS actuators</code> that claims priority to the Australian document. The latest patent grants in 2017 provide the explanation for what has been happening with the family members.</p>
<p>The text of the most recent patent grant US9584681B2 for a <code>Handheld Imaging Device Incorporating Multi-Core Image Processor</code> in the description on related applications says:</p>
<blockquote>
<p>This application is a continuation of U.S. application Ser. No. 13/101,131 filed May 4, 2011, which is a continuation of U.S. application Ser. No. 10/656,791 filed Sep. 8, 2003, issued Jun. 7, 2011, as U.S. Pat. No. 7,957,009, which is a continuation application of U.S. application Ser. No. 09/922,274 filed Aug. 6, 2001, issued Sep. 9, 2003, as U.S. Pat. No. 6,618,117, which is a continuation-in-part application of U.S. application Ser. No. 09/113,053, filed Jul. 10, 1998, issued Mar. 26, 2002, as U.S. Pat. No. 6,362,868. Each of the above identified patents and applications and U.S. Pat. No. 6,238,044 are hereby incorporated herein by reference in their entirety.</p>
</blockquote>
<p>While we have not been able to review the entire portfolio of patent grants, a review of the five most recent documents suggests that the US members of this family have been constructed from a long series of continuation and continuation in part applications.</p>
<p>Further analysis of this specific case is beyond the scope of the Handbook. However, as discussed in the recent in depth review of patent family research by Dechezleprêtre et. al. 2017 it highlights the strategic uses of the patent system with respect to continuation filings <span class="citation">(Dechezleprêtre, Ménière, and Mohnen <a href="#ref-Dechezleprêtre_2017">2017</a>)</span>. Lemley and Moore provide a critique of the use of continuations in the US system and focus on the extreme example of patent activity by a Jerome Lemelson in connection with bar code readers <span class="citation">(Lemley and Moore <a href="#ref-Lemley_2003">2003</a>)</span>. They highlight that using continuations and continuations in part:</p>
<blockquote>
<p>“Inventors can keep an application pending in the PTO for years, all the while monitoring developments in the marketplace. They can then draft claims that will cover those developments. In the most extreme cases, patent applicants add claims during the continuation process to cover ideas they never thought of themselves, but instead learned from a competitor. The most egregious example is Jerome Lemelson, who regularly rewrote claims over the decades his patents were in prosecution in order to cover technologies developed long after he first filed his applications. Lemelson filed eight of the ten continuation patents with the longest delays in prosecution in our study. Those Lemelson patents spent anywhere from thirty-eight to more than forty-four years in the PTO.” <span class="citation">(Lemley and Moore <a href="#ref-Lemley_2003">2003</a>)</span></p>
</blockquote>
<p>As Dechezleprêtre et. al. point out the aspects of US patent law that facilitated the specific strategic behaviour by this applicant have been abolished. However, continuations and continuations in part continue to feature as part of the US patent system.</p>
<p>From the perspective of patent analytics, this example demonstrates that we are able to move from the use of patent family data to explore patent activity linked to a priority filing or set of priorities anywhere in the world. We are also able to identify the top ranking patent families and to explore the details of those families in individual countries. Simple techniques such as the use of a frequency plot over time help us to identify patterns in activity. In the case of Silverbrook we have seen that while the company reportedly went into administration in 2014, with a collapse in US family activity observable in the frequency plots above for that period, we then observe the issuance of patent grants from 2015 into 2017 (the end of our data). This suggests that this portfolio has been taken over (perhaps through the sale of the IP to a third party). To proceed further in the analysis of this case we would want to look at the legal status for the documents in the portfolio. Thus, a review of the legal status for the most recent patent grant US9584681B2 reveals that it is now owned by Google.<a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a>. In addition, as discussed by <span class="citation">(Hall and Harhoff <a href="#ref-Hall_2012">2012</a>)</span> the analysis of patent renewal fees has an important role to play in analysis of the economic value of patent grants within a family portfolio.</p>
<p>The discussion of patent families presented above points to the richness of research that is possible using patent family data. It is important to note that different definitions of patent families are important in patent analytics and may yield different insights. Thus, one criticism of INPADOC patent families is that they are too broad and a simpler more focused definition may be preferred. In other cases as in the work by the OECD the use of trilateral patent families is intended to promote international comparability by removing the home bias in patent data. The use of this type of definition is important for both comparability and identification of more important patents. Thus in the case of countries such as China, where filings are heavily focused on the national level, the selection of patent families with international members can facilitate the analysis of cases where Chinese inventors and applicants may be seeking to invest in external markets.</p>
<p>In closing this discussion it is important to emphasise that patent families continue to be a very active focus of research in economics and innovation studies. As the most recent review of the literature by Dechezleprêtre et. al. 2017 has highlighted to date the main focus in this literature has been on using family size as the indicator of value (focusing on the number of countries represented in a family) the number of filings in the priority country along with the time span between the first and last filings within a family also offer insights into patent value <span class="citation">(Dechezleprêtre, Ménière, and Mohnen <a href="#ref-Dechezleprêtre_2017">2017</a>)</span>. As such, the discussion presented above presents a starting point for engaging with this increasingly rich literature.</p>
</div>
<div id="forecasting-patent-activity" class="section level2">
<h2><span class="header-section-number">3.8</span> Forecasting Patent Activity</h2>
<p>TBD</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-OECD_2009">
<p><em>OECD Patent Statistics Manual</em>. 2009. OECD Publishing. <a href="https://doi.org/10.1787/9789264056442-en" class="uri">https://doi.org/10.1787/9789264056442-en</a>.</p>
</div>
<div id="ref-Hegde_2007">
<p>Hegde, Deepak, David Mowery, and Stuart Graham. 2007. “Pioneers, Submariners, or Thicket-Builders: Which Firms Use Continuations in Patenting?” National Bureau of Economic Research. <a href="https://doi.org/10.3386/w13153" class="uri">https://doi.org/10.3386/w13153</a>.</p>
</div>
<div id="ref-Dechezleprêtre_2017">
<p>Dechezleprêtre, Antoine, Yann Ménière, and Myra Mohnen. 2017. “International Patent Families: From Application Strategies to Statistical Indicators.” <em>Scientometrics</em> 111 (2). Springer Nature: 793–828. <a href="https://doi.org/10.1007/s11192-017-2311-4" class="uri">https://doi.org/10.1007/s11192-017-2311-4</a>.</p>
</div>
<div id="ref-Dernis_2007">
<p>Dernis, Hélène. 2007. “Nowcasting Patent Indicators,” January.</p>
</div>
<div id="ref-Martinez_2010">
<p>Martinez, Catalina. 2010a. “Insight into Different Types of Patent Families.” Organisation for Economic Co-Operation; Development (OECD). <a href="https://doi.org/10.1787/5kml97dr6ptl-en" class="uri">https://doi.org/10.1787/5kml97dr6ptl-en</a>.</p>
</div>
<div id="ref-Dernis_2004">
<p>Dernis, Hélène, and Mosahid Khan. 2004. “Triadic Patent Families Methodology.” Organisation for Economic Co-Operation; Development (OECD). <a href="https://doi.org/10.1787/443844125004" class="uri">https://doi.org/10.1787/443844125004</a>.</p>
</div>
<div id="ref-Criscuolo_2006">
<p>Criscuolo, P. 2006. “The ’Home Advantage’ Effect and Patent Families. A Comparison of Oecd Triadic Patents, the Uspto and the Epo.” <em>Scientometrics</em> 66: 23–41.</p>
</div>
<div id="ref-Sternitzke_2009">
<p>Sternitzke, Christian. 2009. “Defining Triadic Patent Families as a Measure of Technological Strength.” <em>Scientometrics</em> 81 (1). Springer Nature: 91–109. <a href="https://doi.org/10.1007/s11192-009-1836-6" class="uri">https://doi.org/10.1007/s11192-009-1836-6</a>.</p>
</div>
<div id="ref-Martinez_2010a">
<p>Martinez, Catalina. 2010b. “Patent Families: When Do Different Definitions Really Matter?” <em>Scientometrics</em> 86 (1). Springer Nature: 39–63. <a href="https://doi.org/10.1007/s11192-010-0251-3" class="uri">https://doi.org/10.1007/s11192-010-0251-3</a>.</p>
</div>
<div id="ref-Lemley_2003">
<p>Lemley, Mark A., and Kimberly A. Moore. 2003. “Ending Abuse of Patent Continuations.” <em>SSRN Electronic Journal</em>. Elsevier BV. <a href="https://doi.org/10.2139/ssrn.462404" class="uri">https://doi.org/10.2139/ssrn.462404</a>.</p>
</div>
<div id="ref-Hall_2012">
<p>Hall, Bronwyn H., and Dietmar Harhoff. 2012. “Recent Research on the Economics of Patents.” <em>Annual Review of Economics</em> 4 (1). Annual Reviews: 541–65. <a href="https://doi.org/10.1146/annurev-economics-080511-111008" class="uri">https://doi.org/10.1146/annurev-economics-080511-111008</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="6">
<li id="fn6"><p>WIPO Summary of the Paris Convention for the Protection of Industrial Property (1883) <a href="http://www.wipo.int/treaties/en/ip/paris/summary_paris.html" class="uri">http://www.wipo.int/treaties/en/ip/paris/summary_paris.html</a><a href="patents.html#fnref6" class="footnote-back">↩</a></p></li>
<li id="fn7"><p>The observant reader will note that for reasons that are unclear publication of the granted patent in 2016 takes place before the publication of the application in 2017<a href="patents.html#fnref7" class="footnote-back">↩</a></p></li>
<li id="fn8"><p>This common pattern may give rise to the temptation to simply take the first priority number in a sequence of priorities as the earliest priority. However, experience demonstrates that databases are not consistent in listing the earliest filing in this way. The temptation should therefore be resisted.<a href="patents.html#fnref8" class="footnote-back">↩</a></p></li>
<li id="fn9"><p>counts cross validated in Vantage Point in light of the spike in B publications between 2000 and 2001<a href="patents.html#fnref9" class="footnote-back">↩</a></p></li>
<li id="fn10"><p>Source: <a href="https://wiki.piug.org/display/PIUG/Patent+Families#PatentFamilies-WPI" class="uri">https://wiki.piug.org/display/PIUG/Patent+Families#PatentFamilies-WPI</a><a href="patents.html#fnref10" class="footnote-back">↩</a></p></li>
<li id="fn11"><p>Martinez notes that PATSTAT data from the 2008 edition may vary in subsequent editions, for example new documents may be added that increase the size or new data sources may be included in PATSTAT<a href="patents.html#fnref11" class="footnote-back">↩</a></p></li>
<li id="fn12"><p>This example can be identified in <a href="mailto:esp@cenet">esp@cenet</a> with application number JP200944799A <a href="https://worldwide.espacenet.com/publicationDetails/biblio?FT=D&amp;date=20090820&amp;DB=EPODOC&amp;locale=en_EP&amp;CC=JP&amp;NR=2009184358A&amp;KC=A&amp;ND=4" class="uri">https://worldwide.espacenet.com/publicationDetails/biblio?FT=D&amp;date=20090820&amp;DB=EPODOC&amp;locale=en_EP&amp;CC=JP&amp;NR=2009184358A&amp;KC=A&amp;ND=4</a><a href="patents.html#fnref12" class="footnote-back">↩</a></p></li>
<li id="fn13"><p><a href="https://print21.com.au/kia-silverbrook-dumps-name-as-business-gets-thrashed/71812" class="uri">https://print21.com.au/kia-silverbrook-dumps-name-as-business-gets-thrashed/71812</a><a href="patents.html#fnref13" class="footnote-back">↩</a></p></li>
<li id="fn14"><p>Thirty priorities are associated with this patent family. There are two documents that share the earliest date AU19977991A 1997-07-15 and AU19978004A 1997-07-15. <a href="mailto:esp@cenet">esp@cenet</a> lists the earliest priority as AU1997PO08010 19970715. The use of the letter P suggests that this could be some form of provisional filing although we have not been able to trace the use of this kind code in WIPO’s examples for Australia.<a href="patents.html#fnref14" class="footnote-back">↩</a></p></li>
<li id="fn15"><p><a href="mailto:esp@cenet">esp@cenet</a> Legal Status for <a href="https://worldwide.espacenet.com/publicationDetails/inpadoc?CC=US&amp;NR=2013016233A1&amp;KC=A1&amp;FT=D&amp;ND=3&amp;date=20130117&amp;DB=EPODOC&amp;locale=en_EP">US9584681B2</a><a href="patents.html#fnref15" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="literature.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="patstat.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["handbook2.pdf", "handbook2.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
